SECTIONS = {
    "1": "Grundlagen – Pflanzen säen und vermehren (20 P)",
    "2": "Grundlagen – Pflanzen ernähren (20 P)",
    "3": "Grundlagen – Pflanzen pflegen und ernten (20 P)",
    "4": "Schwerpunkt Getreidebau (20 P)",
    "5": "Schwerpunkt Ackerfutterbau (20 P)",
    "6": "Schwerpunkt Grünland (20 P)",
    "7": "Schwerpunkt Waldbau (20 P)",
}

QUESTIONS = [
    dict(
        id="P2020.1",
        section="1",
        topic="Rhizom Quecke",
        frage="Welche Organe dienen bei der Quecke (Elytrigia repens) der vegetativen Vermehrung?",
        antwort="Rhizome (unterirdische Sprosse)",
        falsch=[
            "Sprossknollen mit Augen",
            "Ausläufer über der Erdoberfläche",
            "Nebenwurzeln am Hypokotyl",
        ],
        hinweis="Rhizome sind unterirdische Sprosse, die jahrelang lebensfähig bleiben und zugleich Nährstoffspeicher und vegetative Vermehrungsorgan sind.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 11",
    ),
    dict(
        id="P2021.2",
        section="1",
        topic="Sprossknollen Kartoffel",
        frage="Was sind die Augen der Kartoffel (Solanum tuberosum) botanisch?",
        antwort="Sprosskegel",
        falsch=[
            "Wurzelhaare",
            "Nebenblätter",
            "Kelchblätter",
        ],
        hinweis="Bei der Kartoffel sind die Augen Sprosskegel; am Ende des Sprosses entstehen Stolonen.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 11",
    ),
    dict(
        id="P2022.3",
        section="1",
        topic="Einhäusige Pflanzen",
        frage="Zu welcher Gruppe gehört der Mais (Zea mays) bezüglich der Blütenverteilung?",
        antwort="Einhäusig (männliche und weibliche Blüten an derselben Pflanze)",
        falsch=[
            "Zweihäusig getrenntgeschlechtig",
            "Selbstbefruchter mit Windbestäubung",
            "Zweihäusig weiblich mit männlichen Blüten am Nachbarstock",
        ],
        hinweis="Einhäusig bedeutet: die Pflanze trägt sowohl männliche als auch weibliche Blüten, z. B. Mais. Zweihäusig wäre z. B. Hopfen.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 20",
    ),
    dict(
        id="P2023.4",
        section="1",
        topic="Ährenstand Getreide",
        frage="Welche Pflanzenarten besitzen einen Ährenstand?",
        antwort="Weizen, Gerste, Roggen und Triticale",
        falsch=[
            "Hafer, Mais und Lupine",
            "Weizen, Hafer und Raps",
            "Roggen, Raps und Kartoffel",
        ],
        hinweis="Ähre: Weizen, Gerste, Roggen, Triticale. Rispe: Hafer. Traube: Lupine. Kolben: Mais.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 21",
    ),
    dict(
        id="P2020.5",
        section="1",
        topic="BBCH-Skala",
        frage="Wofür steht die BBCH-Skala?",
        antwort="Sie codiert die Entwicklungsstadien der Pflanze (0 = Korn bis 100 = Pflanze ist tot)",
        falsch=[
            "Sie codiert die Nährstoffgehalte im Boden",
            "Sie codiert die Schadensbonitur von Schädlingen",
            "Sie codiert die Mahd-Reifezahl nach DIN",
        ],
        hinweis="Die Entwicklungsabschnitte werden nach Code-Zahlen eingeteilt, von 0 (Korn) bis 100 (Pflanze ist tot). Die Kenntnis ist für Dünge- und Pflanzenschutzmaßnahmen unbedingt nötig.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 34",
    ),
    dict(
        id="P2021.6",
        section="1",
        topic="Schossen BBCH",
        frage="Welche BBCH-Codenummer hat beim Getreide das Schossen?",
        antwort="3",
        falsch=[
            "5",
            "7",
            "9",
        ],
        hinweis="0 Keimung, 1 Blattentwicklung, 2 Bestockung, 3 Schossen, 4 Ähren-/Rispenschwellen, 5 Ähren-/Rispenschieben, 6 Blüte, 7 Fruchtbildung, 8 Samenreife, 9 Absterben.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 36",
    ),
    dict(
        id="P2022.7",
        section="1",
        topic="Heterosis Hybridmais",
        frage="Worin besteht der Heterosiseffekt bei Hybridmais?",
        antwort="Nachkommen der Elterngeneration sind sehr produktiv, stabil und einheitlich",
        falsch=[
            "Nachkommen der F1-Generation vermischen die vererbten Merkmale vollständig uneinheitlich",
            "Hybridmais bildet auch Sorten mit erhaltener Saatgutvermehrung",
            "Hybridmais ist gegenüber Populationen ertragsärmer, dafür samenbeständig",
        ],
        hinweis="Hybridmais ist eine Kreuzung verschiedener reinerbiger Inzucht-Elternlinien (AA x BB = AB). Vorteil: Heterosiseffekt und Homogenität. Nachteil: jedes Jahr Neukauf, keine eigene Vermehrung möglich.",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 16",
    ),
    dict(
        id="P2023.8",
        section="1",
        topic="Schließfrucht Getreide",
        frage="Zu welchem Fruchttyp zählt das Getreidekorn?",
        antwort="Schließfrucht (Trockenfrucht)",
        falsch=[
            "Springfrucht",
            "Spaltfrucht",
            "Sammelfrucht",
        ],
        hinweis="Trockenfrüchte: Schließfrüchte (Getreidekorn), Springfrüchte (Hülsen, Schoten, Kapseln), Spaltfrüchte (Gliederschoten). Saftige Früchte: Beeren, Steinfrüchte, Sammelfrüchte.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 22",
    ),
    dict(
        id="P2020.9",
        section="2",
        topic="Minimumgesetz Liebig",
        frage="Was besagt das Minimumgesetz nach Justus v. Liebig?",
        antwort="Das Wachstum wird durch den Nährstoff begrenzt, der am wenigsten zur Verfügung steht",
        falsch=[
            "Das Wachstum wird durch den Nährstoff begrenzt, der am reichsten zur Verfügung steht",
            "Alle Nährstoffe können sich gegenseitig voll vertreten",
            "Bei reiner Düngung des Kaliums wird der Ertrag begrenzt",
        ],
        hinweis="Der Nährstoffbedarf ist artverschieden und Nährstoffe können sich nicht gegenseitig vertreten. Nur entzogene Nährstoffe vollständig ersetzt zu werden, hält Böden fruchtbar.",
        quelle="Skripte erste Blockwoche 2025/03_Grundlagen Düngung_BiLa_Reindl_2025.pdf, Folie 3",
    ),
    dict(
        id="P2021.10",
        section="2",
        topic="Nährstoffaufnahme Ionen",
        frage="In welcher Form nimmt die Pflanze Nährstoffe überwiegend aus der Bodenlösung auf?",
        antwort="Als Ionen, z. B. K+, Ca++, Mg++, NO3-, H2PO4-",
        falsch=[
            "Als neutrale Moleküle, z. B. Glucose und Aminosäuren",
            "Als gelöste Kalziumkarbonate in Suspension",
            "Ausschließlich über die Blätter aus der Luft",
        ],
        hinweis="Die Pflanze nimmt Ionen auf und gibt dafür andere Ionen ab (z. B. H+, HCO3-). Ohne Wasser und Saftstrom ist keine Nährstoffaufnahme möglich.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 33",
    ),
    dict(
        id="P2022.11",
        section="2",
        topic="Ionenkonkurrenz Kalzium",
        frage="Welche Folge hat eine hohe Kalziumkonzentration im Boden für die Magnesiumaufnahme?",
        antwort="Die Aufnahme von Mg++ wird behindert (Ionen stehen in Konkurrenz)",
        falsch=[
            "Die Aufnahme von Mg++ wird verstärkt",
            "Kalzium und Magnesium werden gemeinsam bevorzugt aufgenommen",
            "Magnesium verdrängt Kalzium vollständig aus dem Boden",
        ],
        hinweis="Die Ionen stehen untereinander in Konkurrenz. So wird die Aufnahme von Mg++ durch eine hohe Konzentration von Ca++ behindert.",
        quelle="Skripte erste Blockwoche 2025/02_Grundlagen Pflanze_BiLa_Reindl_2025.pdf, Folie 33",
    ),
    dict(
        id="P2023.12",
        section="2",
        topic="Stickstoff in der Gülle",
        frage="Wie setzt sich der Stickstoff in einer Gülle zusammen?",
        antwort="Etwa zur Hälfte als Ammonium und zur Hälfte organisch gebunden",
        falsch=[
            "Überwiegend als Nitrat und Kalium",
            "Ausschließlich organisch gebunden",
            "Zur Hälfte als Harnstoff und zur Hälfte als Ammoniak",
        ],
        hinweis="Die Gülle enthält nur etwa die Hälfte des Stickstoffs als pflanzenverfügbares Ammonium; der organisch gebundene Anteil wird erst durch Mineralisierung im Boden verfügbar.",
        quelle="Skripte erste Blockwoche 2025/03_Grundlagen Düngung_BiLa_Reindl_2025.pdf, Folie 30",
    ),
    dict(
        id="P2020.13",
        section="2",
        topic="Erhaltungskalkung Acker",
        frage="Welche Menge CaO ist für die Erhaltungskalkung auf Ackerland in 3 Jahren nötig?",
        antwort="17 dt/ha CaO",
        falsch=[
            "5 dt/ha CaO",
            "25 dt/ha CaO",
            "1 dt/ha CaO",
        ],
        hinweis="17 dt/ha CaO entsprechen etwa 2,0 t/ha Branntkalk (85 % CaO) bzw. 3,27 t/ha kohlensaurem Kalk (52 % CaO). Auf Grünland beträgt die Erhaltungskalkung 5 dt/ha CaO in 3 Jahren.",
        quelle="Skripte erste Blockwoche 2025/03_Grundlagen Düngung_BiLa_Reindl_2025.pdf, Folie 26",
    ),
    dict(
        id="P2021.14",
        section="2",
        topic="Schwefel im Boden",
        frage="In welcher Form kann die Pflanze Schwefel aufnehmen?",
        antwort="Nur als Sulfat (SO42-)",
        falsch=[
            "Als Sulfit (SO32-)",
            "Als elementarer Schwefel",
            "Als Thiosulfat (S2O32-)",
        ],
        hinweis="Der größte Teil des Bodenvorrats an Schwefel (>75 %) ist in organischer Substanz gebunden und muss erst mineralisiert werden. Sulfat kann als negativ geladenes Ion nicht an den Sorptionskomplex gebunden werden – daher besteht Auswaschungsgefahr.",
        quelle="Skripte erste Blockwoche 2025/03_Grundlagen Düngung_BiLa_Reindl_2025.pdf, Folie 65",
    ),
    dict(
        id="P2022.15",
        section="2",
        topic="Spurennährstoff Eisen",
        frage="Wie hoch ist der Entzug an Eisen (Fe) von 1 ha Winterweizen bei Ø-Ertrag?",
        antwort="960 g/ha",
        falsch=[
            "4 g/ha",
            "45 g/ha",
            "350 g/ha",
        ],
        hinweis="Entzug in g/ha bei Ø-Ertrag: Bor 30, Zink 350, Mangan 500, Kupfer 45, Eisen 960, Molybdän 4.",
        quelle="Skripte erste Blockwoche 2025/03_Grundlagen Düngung_BiLa_Reindl_2025.pdf, Folie 70",
    ),
    dict(
        id="P2023.16",
        section="2",
        topic="Ziel-pH-Wert Acker",
        frage="Welcher pH-Wert wird für leichtbödenes Ackerland anzustreben?",
        antwort="5,4 bis 6,2",
        falsch=[
            "6,6 bis 7,2",
            "4,8 bis 5,2",
            "7,5 bis 8,0",
        ],
        hinweis="Anzustrebende pH-Werte Acker: leicht 5,4-6,2, mittel 6,2-6,8, schwer 6,6-7,2. Grünland liegt mit 5,1-6,3 darunter.",
        quelle="Skripte erste Blockwoche 2025/01_Grundlagen_Boden_BiLa_Reindl_2025.pdf, Folie 55",
    ),
    dict(
        id="P2020.17",
        section="3",
        topic="Definition Pflanzenschutzmittel",
        frage="Welche Aussage zum Begriff Pflanzenschutzmittel ist zutreffend?",
        antwort="Es beeinflusst die Lebensvorgänge von Pflanzen, ohne ihnen zur Ernährung zu dienen",
        falsch=[
            "Es versorgt die Pflanze mit Nährstoffen und erhöht den Ertrag",
            "Es zählt zu den Pflanzenstärkungsmitteln wie Gesteinsmehl",
            "Es wirkt ausschließlich gegen nichtparasitäre Beeinträchtigungen",
        ],
        hinweis="Pflanzenschutzmittel schützen Pflanzen und Pflanzenerzeugnisse vor Schadorganismen, beeinflussen Lebensvorgänge ohne zur Ernährung zu dienen (z. B. Wachstumsregler), hemmen die Keimung oder töten Pflanzen ab. Pflanzenstärkungsmittel zählen nicht dazu.",
        quelle="Skripte erste Blockwoche 2025/PS-Sk_theorie_Weilheim_2025.pdf, Folie 101",
    ),
    dict(
        id="P2021.18",
        section="3",
        topic="Auflagenkürzung NW",
        frage="Wofür steht die Auflage-Kurzbezeichnung NW in der Pflanzenschutzmittel-Kennzeichnung?",
        antwort="Naturhaushalt Oberflächenwasser",
        falsch=[
            "Naturhaushalt Grundwasser",
            "Naturhaushalt Bienenschutz",
            "Naturhaushalt Nichtziel-Organismen",
        ],
        hinweis="NG = Naturhaushalt Grundwasser, NW = Naturhaushalt Oberflächenwasser, NB = Naturhaushalt Bienenschutz, NT = Naturhaushalt Nichtziel-Organismen (Schutz terrestrischer Biozönosen).",
        quelle="Skripte erste Blockwoche 2025/PS-Sk_theorie_Weilheim_2025.pdf, Folie 125",
    ),
    dict(
        id="P2022.19",
        section="3",
        topic="Auflagenkürzung NT",
        frage="Wofür steht die Auflage-Kurzbezeichnung NT in der Pflanzenschutzmittel-Kennzeichnung?",
        antwort="Naturhaushalt Nichtziel-Organismen (Schutz terrestrischer Biozönosen)",
        falsch=[
            "Naturhaushalt Terrestrische Organismen bei Nacht",
            "Naturhaushalt Oberflächenwasser",
            "Nicht targetorganismen – Verbot der Ausbringung bei Nacht",
        ],
        hinweis="NG Grundwasser, NW Oberflächenwasser, NB Bienenschutz, NT Nichtziel-Organismen. Weitere Auflagen: NH, NO, VV.",
        quelle="Skripte erste Blockwoche 2025/PS-Sk_theorie_Weilheim_2025.pdf, Folie 125",
    ),
    dict(
        id="P2023.20",
        section="3",
        topic="Einarbeitung organische Düngung",
        frage="Innerhalb welcher Frist müssen organische Düngemittel mit wesentlichem Anteil an verfügbarem Stickstoff auf unbestelltes Ackerland eingearbeitet werden (Regelung ab 01.02.2025)?",
        antwort="Innerhalb 1 Stunde nach Beginn des Aufbringens",
        falsch=[
            "Innerhalb 24 Stunden",
            "Innerhalb 4 Stunden",
            "Innerhalb 10 Tagen",
        ],
        hinweis="Ab 01.02.2025: Einarbeitung innerhalb 1 Stunde für alle organischen Düngemittel über 2 % TS mit wesentlichem Anteil an verfügbarem Stickstoff, außer Festmist von Huf- und Klauentieren und Kompost. Ab 2020 gilt: Harnstoff nur mit Ureasehemmer oder Einarbeitung binnen 4 Stunden.",
        quelle="Skripte erste Blockwoche 2025/04_Gesetzliche Grundlagen Pflanzenbau_BiLa_Reindl_2025.pdf, Folie 58",
    ),
    dict(
        id="P2020.21",
        section="3",
        topic="Schadschwelle Pflanzenschutz",
        frage="Wann ist eine Pflanzenschutzmaßnahme laut Bekämpfungsschwelle wirtschaftlich sinnvoll?",
        antwort="Bei Überschreiten der Schadschwelle",
        falsch=[
            "Bei vollständig sichtbarem Schadausbild am Bestand",
            "Bei jedem Auftreten des Schädlings",
            "Bei Unterschreiten der Bekämpfungsschwelle",
        ],
        hinweis="Schadschwelle: Schäden des Schädlingsbefalls bei Unterlassen sind genauso hoch wie die Kosten der Pflanzenschutzmaßnahme. Oft kann nicht bis zum Erreichen der Schadschwelle gewartet werden – dann greift die Bekämpfungsschwelle.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 58",
    ),
    dict(
        id="P2021.22",
        section="3",
        topic="Kornfeuchte Lagerung",
        frage="Welche Kornfeuchte sollte beim Getreide nach der Ernte vor der Lagerung erreicht werden?",
        antwort="Unter 14 %, andernfalls trocknen",
        falsch=[
            "Über 14,5 %",
            "Genau 18 %",
            "Über 20 %",
        ],
        hinweis="Der Feuchtegehalt sollte < 14 % sein, da sonst Schimmel-, Bakterien- und Hefepilzbildung gefördert werden. Handelsanforderung Feuchte: max. 14,5 %.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 94",
    ),
    dict(
        id="P2022.23",
        section="3",
        topic="Striegelwirkung Keimblatt",
        frage="Wie hoch ist der Wirkungsgrad des Striegelns gegen Unkräuter im Keimblattstadium?",
        antwort="80 bis 90 %",
        falsch=[
            "50 bis 55 %",
            "70 bis 75 %",
            "17 %",
        ],
        hinweis="Wirkung des Striegels nach Entwicklungsstadium des Unkrauts: Keimblatt 80-90 %, kleine Rosette 70-75 %, große Rosette 50-55 %. Je früher die Unkräuter erfasst werden, desto besser der Wirkungsgrad.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 70",
    ),
    dict(
        id="P2023.24",
        section="3",
        topic="PSM Grundsatz",
        frage="Welcher Grundsatz gilt allgemein beim Pflanzenschutz im Getreidebau?",
        antwort="So wenig wie möglich, so viel wie nötig",
        falsch=[
            "So früh wie möglich, so viel wie möglich",
            "So teuer wie möglich, so lange wie nötig",
            "Möglichst nur chemisch, mechanische Verfahren sind unwirksam",
        ],
        hinweis="Pflanzenschutzmaßnahmen immer nach dem Schadschwellenprinzip anwenden, Kombination von chemischen und mechanischen Verfahren, auf örtliche Gegebenheiten achten (Gewässerabstände, Abstand zu Nicht-Zielflächen, Wirkdauer, Resistenzen).",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 58",
    ),
    dict(
        id="P2020.25",
        section="4",
        topic="Saatmenge Winterweizen",
        frage="Wie hoch ist die Saatgutmenge bei 330 Körner/m², 46 g Tausendkorngewicht und 95 % Keimfähigkeit?",
        antwort="160 kg/ha",
        falsch=[
            "144 kg/ha",
            "179 kg/ha",
            "240 kg/ha",
        ],
        hinweis="Rechenweg: 330 Körner/m² x 46 g Tausendkorngewicht / 0,95 Keimfähigkeit = 16,0 g/m² = 160 kg/ha Saatgutmenge.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 52",
    ),
    dict(
        id="P2021.26",
        section="4",
        topic="Saatmenge Saatgutpartie",
        frage="Welche Saatgutmenge ergibt sich für eine Saatgutpartie mit 96 % Keimfähigkeit und 42 g Tausendkorngewicht bei 330 Körner/m²?",
        antwort="144 kg/ha",
        falsch=[
            "131 kg/ha",
            "179 kg/ha",
            "126 kg/ha",
        ],
        hinweis="Rechenweg: 330 Körner/m² x 42 g Tausendkorngewicht / 0,96 Keimfähigkeit = 14,44 g/m² = 144 kg/ha Saatgutmenge.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 52",
    ),
    dict(
        id="P2022.27",
        section="4",
        topic="Saatzeit Winterweizen",
        frage="Was ist die optimale Saatzeit für Winterweizen?",
        antwort="Anfang Oktober bis Mitte November",
        falsch=[
            "Anfang März bis Ende April",
            "Mitte Juli bis Ende August",
            "Ende September bis Mitte Oktober",
        ],
        hinweis="Saatzeiträume Winterweizen: optimal Anfang Oktober bis Mitte November, möglich Oktober bis Ende Dezember.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 48",
    ),
    dict(
        id="P2023.28",
        section="4",
        topic="Ertragszusammensetzung",
        frage="Welcher Ertrag wird bei 500 Ähren/m², 40 Körner je Ähre und 45 g Tausendkorngewicht erreicht?",
        antwort="90 dt/ha",
        falsch=[
            "45 dt/ha",
            "180 dt/ha",
            "900 dt/ha",
        ],
        hinweis="Rechenweg: 500 Ähren/m² x 45 g x 40 Körner = 900.000 g/m²; 900.000 / 10.000 m²/ha = 90 dt/ha.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 46",
    ),
    dict(
        id="P2020.29",
        section="4",
        topic="Bekämpfungsschwelle Septoria",
        frage="Welche Bekämpfungsschwelle gilt für Septoria tritici im Weizen?",
        antwort="8 von 20 Pflanzen befallen (40 % Befallshäufigkeit)",
        falsch=[
            "12 von 20 Pflanzen befallen (60 % Befallshäufigkeit)",
            "3 von 20 Pflanzen befallen (15 % Befallshäufigkeit)",
            "20 von 20 Pflanzen befallen (100 % Befallshäufigkeit)",
        ],
        hinweis="Bekämpfungsschwelle Weizen: Septoria tritici 8 von 20 Pflanzen befallen (40 % Befallshäufigkeit), Mehltau 12 von 20 Pflanzen befallen.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 60",
    ),
    dict(
        id="P2021.30",
        section="4",
        topic="Bekämpfungsschwelle Mehltau",
        frage="Welche Bekämpfungsschwelle gilt für Mehltau im Weizen?",
        antwort="12 von 20 Pflanzen befallen",
        falsch=[
            "8 von 20 Pflanzen befallen",
            "2 von 20 Pflanzen befallen",
            "5 von 20 Pflanzen befallen",
        ],
        hinweis="Septoria tritici: 8 von 20 Pflanzen (40 %). Mehltau: 12 von 20 Pflanzen. Bei Überschreiten der Schadschwelle ist die Bekämpfung wirtschaftlich sinnvoll.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 60",
    ),
    dict(
        id="P2022.31",
        section="4",
        topic="B-Weizen Proteingehalt",
        frage="Welcher Proteingehalt wird als übliche Handelsanforderung für B-Weizen gefordert?",
        antwort="Über 11,5 %",
        falsch=[
            "Über 14 %",
            "Über 13 %",
            "Über 8 %",
        ],
        hinweis="Übliche Handelsanforderung Proteingehalt: E-Weizen > 14 %, A-Weizen > 13 %, B-Weizen > 11,5 %. Handelsanforderungen können je nach Jahr schwanken; gesetzliche Anforderungen gibt es nicht.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 84",
    ),
    dict(
        id="P2023.32",
        section="4",
        topic="E-Weizen",
        frage="Wie wird E-Weizen im Getreidehandel charakterisiert?",
        antwort="Eliteweizen mit höchstem Aufmischwert",
        falsch=[
            "Futterweizen mit niedrigem Proteingehalt",
            "Backweizen zum eigenständigen Backen ohne Mischen",
            "Keksweizen mit sehr hohem Kleberanteil",
        ],
        hinweis="Qualitätsstufen Weizen: E-Weizen Eliteweizen mit höchstem Aufmischwert, A-Weizen Aufmischweizen, B-Weizen Backweizen, C-Weizen Futterweizen, K-Weizen Keksweizen.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 84",
    ),
    dict(
        id="P2020.33",
        section="4",
        topic="Hektolitergewicht Getreide",
        frage="Welches Mindest-Hektolitergewicht wird für Getreide gefordert?",
        antwort="76 kg/hl",
        falsch=[
            "67 kg/hl",
            "45 kg/hl",
            "96 kg/hl",
        ],
        hinweis="Qualitätskriterien Getreide allgemein: Feuchte max. 14,5 %, Bruchkorn max. 4 %, Kornbesatz max. 2 %, Auswuchs max. 2 %, Hektolitergewicht mind. 76 kg/hl, gesund und frei von Pilzgiften.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 88",
    ),
    dict(
        id="P2021.34",
        section="4",
        topic="Ackerfuchsschwanz Ertragsverlust",
        frage="Welchen Ertragsverlust verursachen 100 Ackerfuchsschwanz-Ähren je m² im Getreide?",
        antwort="Etwa 4 bis 5 dt/ha",
        falsch=[
            "Etwas 40 bis 50 dt/ha",
            "Etwa 0,4 bis 0,5 dt/ha",
            "Etwa 14 bis 15 dt/ha",
        ],
        hinweis="100 AFS-Ähren/m² führen zu ca. 4-5 dt/ha Ertragsverlust. Gegenmaßnahmen: spätere Aussaat, Grundbodenbearbeitung (Pflug), vielfältige Fruchtfolge, mechanische Unkrautbekämpfung, Reinigung des Mähdreschers.",
        quelle="grundlagen getreidebau/01_Grundlagen Getreidebau BiLa 2026.pdf, Folie 68",
    ),
    dict(
        id="P2022.35",
        section="5",
        topic="Feldfutterbau Definition",
        frage="Wie lautet die Definition des Feldfutterbaus?",
        antwort="Feldmäßiger Anbau zur Gewinnung von (Rau-)Futter zur Frischfütterung, Vergärung oder Trocknung",
        falsch=[
            "Anbau von Gräsern und Klee auf Dauergrünlandflächen",
            "Anbau von Silomais und Futterrüben zur Gärgasproduktion",
            "Anbau von Zwischenfrüchten zum Zweck der Gründüngung",
        ],
        hinweis="Feldfutterbau = feldmäßiger Anbau zur Gewinnung von (Rau-)Futter zur Frischfütterung, Vergärung oder Trocknung. Er wird der Ackerbau zugeordnet, nicht dem Dauergrünland.",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 102",
    ),
    dict(
        id="P2023.36",
        section="5",
        topic="Ackerfutter Anteil Bayern",
        frage="Welchen Anteil an den Ackerflächen Bayerns hat der Hauptfrucht-Feldfutterbau (ohne Silomais und Futterrüben)?",
        antwort="5 bis 6 %",
        falsch=[
            "20 bis 25 %",
            "30 bis 35 %",
            "unter 1 %",
        ],
        hinweis="Hauptfrucht-Feldfutterbau: Anteil 5-6 % der Ackerflächen in Bayern (ohne Silomais und Futterrüben). Der Zwischenfruchtfutterbau nimmt dagegen 30 % der Ackerflächen ein.",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 104",
    ),
    dict(
        id="P2020.37",
        section="5",
        topic="Humusmehrung Fruchtfolge",
        frage="Ab welchem Anteil an der Fruchtfolge wird laut Zielsetzung des Hauptfrucht-Futterbaus eine Humusmehrung der Böden erreicht?",
        antwort="Ab 30 % Anteil an der Fruchtfolge",
        falsch=[
            "Ab 10 % Anteil an der Fruchtfolge",
            "Ab 50 % Anteil an der Fruchtfolge",
            "Ab 5 % Anteil an der Fruchtfolge",
        ],
        hinweis="Ziele des Hauptfrucht-Futterbaus: Futtererzeugung, Humusmehrung der Böden ab 30 % Anteil an Fruchtfolge, N-Mehrung (Nmin im Frühjahr bis > 100 kg N/ha), Problemunkrauterbekämpfung, Erosions- und Grundwasserschutz, Fruchtfolgeauflockerung.",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 105",
    ),
    dict(
        id="P2021.38",
        section="5",
        topic="Silierung pH-Wert",
        frage="Auf welchen pH-Wert fällt der pH-Wert einer stabilen Silage typischerweise?",
        antwort="4,0 bis 4,5",
        falsch=[
            "6,5 bis 7,0",
            "2,5 bis 3,0",
            "7,5 bis 8,0",
        ],
        hinweis="Milchsäurebakterien wandeln Zucker bzw. Stärke in Säuren (v. a. Milchsäure, später Essigsäure) um, der pH-Wert fällt auf typischerweise 4,0-4,5. Dadurch werden gärschädliche Bakterien wie Clostridien (Buttersäure) gehindert.",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 90",
    ),
    dict(
        id="P2022.39",
        section="5",
        topic="Silierung Trockensubstanz",
        frage="Welcher Trockensubstanzgehalt (TS) ist beim Silieren praktisch?",
        antwort="28 bis 35 %",
        falsch=[
            "10 bis 15 %",
            "55 bis 65 %",
            "5 bis 10 %",
        ],
        hinweis="Zu hohe TS-Gehalte erschweren die Verdichtung; praktikable TS: 28-35 %. Zu hohe Wassergehalte (TS < 28 %) wirken einem niedrigen pH-Wert entgegen (Puffervermögen des Wassers, geringe Nährstoff- und Zuckerkonzentration).",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 92",
    ),
    dict(
        id="P2023.40",
        section="5",
        topic="Gärdauer Silo",
        frage="Wie lange sollte der Silostock mindestens unter Luftabschluss bleiben?",
        antwort="Mindestens 4 Wochen, besser 6 Wochen",
        falsch=[
            "Mindestens 4 Stunden, besser 12 Stunden",
            "Mindestens 6 Monate, besser 12 Monate",
            "Sofort nach dem Befüllen öffnen",
        ],
        hinweis="Zu frühes Öffnen des Silostocks ist ein Silierproblem (mind. 4, besser 6 Wochen Gärdauer unter Luftabschluss). Ein geringer Vorschub führt zu Nacherwärmung: Empfehlung 1,5 m/Woche im Winter, 2,5 m/Woche im Sommer.",
        quelle="BiLa 25-27_Ackerfutterbau und Konservierung ohne Getreide_Schäfer.pdf, Folie 93",
    ),
    dict(
        id="P2020.41",
        section="6",
        topic="Futterwertzahl Stufen",
        frage="Wieviele Stufen umfasst die Futterwertzahl (WZ)?",
        antwort="8 Stufen",
        falsch=[
            "5 Stufen",
            "10 Stufen",
            "3 Stufen",
        ],
        hinweis="Die Futterwertzahl (WZ) hat 8 Stufen; die Reaktionszahl (RZ) hat 5 Stufen (1 = sauer, 5 = alkalisch).",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern.pdf, Seite 39-40",
    ),
    dict(
        id="P2021.42",
        section="6",
        topic="Herbstzeitlose WZ",
        frage="Welche Futterwertzahl (WZ) hat die Herbstzeitlose im Grünland?",
        antwort="-1 (wertlos bis sehr geringwertig)",
        falsch=[
            "+5 (sehr wertvoll)",
            "+3 (hochwertig)",
            "+8 (sehr wertvolle Futterpflanze)",
        ],
        hinweis="Unkräuter des Grünlandes mit Futterwertzahl: Ampfer 1, Brennnessel 1, Storchschnabel 2, Giersch 3, Wiesenlabkraut 3, Landwasserknöterich 2, Kratzdistel 0, Herbstzeitlose -1, Kreuzkraut -1, Wiesenschaumkraut -1, Scharfer Hahnenfuß -1/1.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 3.pdf, Seite 54",
    ),
    dict(
        id="P2022.43",
        section="6",
        topic="Herbstzeitlose Giftwert",
        frage="Welchen kritischen Wert nennt das Skript für die Giftigkeit der Herbstzeitlose?",
        antwort="2 %",
        falsch=[
            "0,2 %",
            "20 %",
            "0,02 %",
        ],
        hinweis="Herbstzeitlose: Gift-Wirkung Durchfall, Atemlähmung, Tod; kritischer Wert 2 %. Sie ist ein Lichtkeimer – frühe Mahd führt zum Aussamen.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 4.pdf, Seite 64",
    ),
    dict(
        id="P2023.44",
        section="6",
        topic="Sperrfrist Grünland",
        frage="In welchem Zeitraum besteht für flüssige organische Dünger (außer Festmist und Kompost) auf Grünland eine Sperrfrist?",
        antwort="1. November bis 31. Januar",
        falsch=[
            "1. Februar bis 30. April",
            "15. Mai bis 15. Juli",
            "1. August bis 30. September",
        ],
        hinweis="Die Sperrfrist für Jauche, Biogassubstrat etc. beginnt am 1. November und endet am 31. Januar. Für Festmist gibt es eine Sperrfrist vom 1.12. bis 15.1.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 2.pdf, Seite 4",
    ),
    dict(
        id="P2020.45",
        section="6",
        topic="Optimale Schnitthöhe",
        frage="Welche optimale Schnitthöhe wird beim Grünlandschnitt angegeben?",
        antwort="7 bis 8 cm",
        falsch=[
            "2 bis 3 cm",
            "12 bis 15 cm",
            "15 bis 20 cm",
        ],
        hinweis="Optimale Schnitthöhe 7-8 cm. Ein zu kurzer Schnitt (zu tief eingestelltes Messer) fördert Verschmutzung im Aufwuchs und Narbenschäden.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern.pdf, Seite 57-58",
    ),
    dict(
        id="P2021.46",
        section="6",
        topic="Reaktionszahl Stufen",
        frage="Wieviele Stufen hat die Reaktionszahl (RZ) und was bedeuten die Extreme?",
        antwort="5 Stufen, 1 = sauer und 5 = alkalisch",
        falsch=[
            "8 Stufen, 1 = alkalisch und 8 = sauer",
            "5 Stufen, 1 = alkalisch und 5 = sauer",
            "3 Stufen, 1 = neutral und 3 = stark basisch",
        ],
        hinweis="Reaktionszahl (RZ, 5 Stufen): 1 = sauer, 5 = alkalisch. Die Futterwertzahl (WZ) hat demgegenüber 8 Stufen.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern.pdf, Seite 39",
    ),
    dict(
        id="P2022.47",
        section="6",
        topic="Gräseranteil Dauergrünland",
        frage="Welchen Anteil an Gräsern nennt das Skript als Ziel für die Bestandeszusammensetzung des Dauergrünlands?",
        antwort="60 bis 70 % Gräser",
        falsch=[
            "10 bis 20 % Gräser",
            "80 bis 90 % Gräser",
            "30 bis 40 % Gräser",
        ],
        hinweis="Optimale Bestandeszusammensetzung des Dauergrünlands: 60-70 % Gräser, dazu Leguminosen und Kräuter. Alles was hart im Bestand steht und die Mähtechnik stört (z. B. Trespe) ist abzudüngen oder zu entfernen.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern.pdf, Seite 42",
    ),
    dict(
        id="P2023.48",
        section="6",
        topic="Nachsaat Niederschlag",
        frage="Welche Bedingung nennt das Skript für die Eignung von Weidelgras zur Nachsaat im Dauergrünland?",
        antwort="Weidelgras ist geeignet, bei mehr als 750 l/m² Jahresniederschlag wird die Nachsaat aber schwierig",
        falsch=[
            "Weidelgras ist ungeeignet, sobald der Jahresniederschlag 750 l/m² überschreitet",
            "Weidelgras ist nur bei Jahresniederschlägen unter 400 l/m² für die Nachsaat geeignet",
            "Weidelgras ist zur Nachsaat ungeeignet, weil es keine Lücken im Bestand benötigt",
        ],
        hinweis="Nachsaat mit Weidelgras geeignet, aber > 750 l/m² Niederschlag. Eine Nachsaat/Übersaat benötigt immer Lücken im Bestand. Grünlandumstellungsprozesse dauern mehrere Jahre.",
        quelle="konservierung grünland/Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 4.pdf, Seite 92",
    ),
    dict(
        id="P2020.49",
        section="7",
        topic="Raum- und Festmeter",
        frage="Wie viel Festmeter (fm) entspricht ein Raummeter (rm) Holz?",
        antwort="1 rm = 0,7 fm",
        falsch=[
            "1 rm = 1,4 fm",
            "1 rm = 0,5 fm",
            "1 rm = 2,0 fm",
        ],
        hinweis="1 Raummeter (rm) = 0,7 Festmeter (fm); 1 Festmeter = 1,4 Raummeter.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa_Holz_Arbeitssicherheit.pdf, Folie 11",
    ),
    dict(
        id="P2021.50",
        section="7",
        topic="Stammvolumen d quadrat",
        frage="Wie hoch ist das Einzelstammvolumen nach der Faustformel d² x L x 0,8 bei 30 cm Mittendurchmesser und 10 m Länge?",
        antwort="0,72 fm",
        falsch=[
            "0,15 fm",
            "1,42 fm",
            "0,71 fm",
        ],
        hinweis="Rechenweg: 0,3 x 0,3 x 10 x 0,8 = 0,72 fm. Zum Vergleich: liegend exakt r² x π x L = 0,15 x 0,15 x 3,14 x 10 = 0,71 fm.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa_Holz_Arbeitssicherheit.pdf, Folie 11",
    ),
    dict(
        id="P2022.51",
        section="7",
        topic="Rindenabzug Fichte",
        frage="Welcher Rindenabzug wird bei der Vermessung ohne Rinde bei Fichte ab einem Mittendurchmesser von 51 cm angesetzt?",
        antwort="3 cm",
        falsch=[
            "1 cm",
            "2 cm",
            "4 cm",
        ],
        hinweis="Rindenabzug Fichte: bis 26 cm = 1 cm, 27-50 cm = 2 cm, ab 51 cm = 3 cm. Tanne: bis 22 cm = 1 cm, 23-38 cm = 2 cm, 38-55 cm = 3 cm, ab 56 cm = 4 cm.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa_Holz_Arbeitssicherheit.pdf, Folie 10",
    ),
    dict(
        id="P2023.52",
        section="7",
        topic="PSA Waldarbeit",
        frage="Welcher Gegenstand gehört zur verpflichtenden Persönlichen Schutzausrüstung (PSA) bei der Waldarbeit?",
        antwort="Schutzhose mit Schnittschutz",
        falsch=[
            "Schnellverschluss-Knopfhemd",
            "Wetterfeste Regenhose ohne Schnittschutz",
            "Motorradhelm mit Visier",
        ],
        hinweis="Die PSA umfasst sieben Teile und muss getragen werden: Schutzhelm, Gesichtsschutz, Gehörschutz, Arbeitsjacke, Schutzhose mit Schnittschutz, Sicherheitsschuhe, Arbeitshandschuhe.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa_Holz_Arbeitssicherheit.pdf, Folie 22",
    ),
    dict(
        id="P2020.53",
        section="7",
        topic="Wiederaufforstungsfrist",
        frage="In welchem Zeitraum muss eine kahlgeschlagene oder unbestockte Waldfläche wieder aufgeforstet werden?",
        antwort="Innerhalb von drei Jahren",
        falsch=[
            "Innerhalb von zwei Jahren",
            "Innerhalb von zehn Jahren",
            "Innerhalb von sechs Monaten",
        ],
        hinweis="Wiederaufforstungspflicht (Art. 15 BayWaldG): kahlgeschlagene oder infolge von Schäden unbestockte Waldflächen sind innerhalb von drei Jahren wieder aufzuforsten; unvollständige Verjüngungen sind innerhalb von fünf Jahren zu ergänzen.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldrecht_NatSch_Jagd_Förderung.pdf, Folie 7",
    ),
    dict(
        id="P2021.54",
        section="7",
        topic="Waldbegriff",
        frage="Wie lautet die gesetzliche Definition von Wald nach Art. 2 BayWaldG?",
        antwort="Jede mit Waldbäumen bestockte oder wiederaufzuforstende Fläche",
        falsch=[
            "Jede mit geschlossener Baumkrone bewachsene Fläche von mehr als einem Hektar",
            "Jede Fläche, die im Flächenwidmungsplan als Wald ausgewiesen ist",
            "Jede bewaldete Fläche mit einem Grundbesitz von mehr als 5000 m²",
        ],
        hinweis="Wald ist jede mit Waldbäumen bestockte oder wiederaufzuforstende Fläche. Dem Wald stehen unter anderem gleich: Waldwege und -lichtungen, Holzlagerplätze, Wildäsungsflächen. Kein Wald: Kurzumtriebs-, Christbaum- und Schmuckreisigkulturen in Feld und Flur.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldrecht_NatSch_Jagd_Förderung.pdf, Folie 3",
    ),
    dict(
        id="P2022.55",
        section="7",
        topic="Borkenkäfer Zyklus",
        frage="Wie lange dauert der Entwicklungszyklus des Buchdruckers von der Eiablage bis zum Ausschwärmen der Jungkäfer?",
        antwort="6 bis 10 Wochen",
        falsch=[
            "6 bis 10 Monate",
            "2 bis 3 Jahre",
            "24 bis 48 Stunden",
        ],
        hinweis="Der Entwicklungszyklus (Eiablage bis Ausschwärmen der Jungkäfer) dauert 6-10 Wochen. Das Vermehrungspotential ist enorm: ein Käferweibchen kann pro Jahr bis zu 100.000 Nachkommen produzieren.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldbau_Waldschutz.pdf, Folie 56",
    ),
    dict(
        id="P2023.56",
        section="7",
        topic="Pheromonfallen Waldschutz",
        frage="Welche Funktion haben Pheromonfallen im Buchdrucker-Monitoring?",
        antwort="Sie dienen der Überwachung der Käferaktivität, nicht der Bekämpfung",
        falsch=[
            "Sie bekämpfen den Buchdrucker durch pheromongesteuerte Anlockung und Vernichtung",
            "Sie locken Förderinsekten an und verbessern so die biologische Schädlingsregulation",
            "Sie messen den Zuwachs des Bestandes",
        ],
        hinweis="Pheromonfallen (Schlitzfallen mit Pheromonköder) dienen nicht der Bekämpfung, sondern der Überwachung der Käferaktivität (Schwärmaktivität, Ausgangsdichte). Geeignete Aufstellungsorte: Bestandesränder und größere Lücken, Sicherheitsabstand zum gesunden Wald mindestens 30 m.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldbau_Waldschutz.pdf, Folie 68",
    ),
]
