"""Fragen der BiLa-Abschlussprüfung im Prüfungsfach Tierproduktion (2020–2023).

Antworten belegt aus dem Unterrichtsmaterial in bila_25-27/.
Nicht belegbare Aufgaben (Abbildungen, fehlende Zahlenwerte im PDF) sind
bewusst nicht enthalten.
"""

SECTIONS = {
    "1": "Grundlagen – Tiere halten und pflegen (20 P)",
    "2": "Grundlagen – Tiere füttern (20 P)",
    "3": "Grundlagen – Tiere züchten (20 P)",
    "4": "Schwerpunkt Milchviehhaltung (20 P)",
    "5": "Schwerpunkt Kälber- und Jungviehhaltung (20 P)",
    "6": "Schwerpunkt Ferkelerzeugung und Schweinemast (20 P)",
}

QUESTIONS = [
    # ---------------- 1. Tiere halten und pflegen ----------------
    dict(
        id="T2023.1", section="1", topic="Kälberverluste",
        frage="Welchen Zielwert sollte man für die Kälberverluste im Betrieb anstreben?",
        antwort="Weniger als 5 % der geborenen Kälber",
        falsch=[
            "Weniger als 15 % der geborenen Kälber",
            "Genau 10 % der geborenen Kälber",
            "Weniger als 1 % der geborenen Kälber",
        ],
        hinweis="Ein Betrieb mit 10,5 % Kälberverlusten (davon rund 7 % während der Aufzucht) liegt über dem Zielwert.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 1.1 (Musterlösung)",
    ),
    dict(
        id="T2021.1", section="1", topic="Schadgase",
        frage="Welchen Höchstwert darf die Ammoniakkonzentration (NH3) im Aufenthaltsbereich von Kälbern nicht überschreiten?",
        antwort="20 ppm",
        falsch=["5 ppm", "50 ppm", "100 ppm"],
        hinweis="Die Merkblattwerte im Kälberstall lauten NH3 20 ppm, CO2 3000 ppm und H2S 5 ppm.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 6 Stallklima",
    ),
    dict(
        id="T2022.1", section="1", topic="Stallklima",
        frage="Welche Temperaturanforderung gilt für den Liegebereich von Kälbern (Ausnahme Kaltställe und Kälberhütten)?",
        antwort="Maximal 25,0 °C, in den ersten 10 Lebenstagen mindestens 10,0 °C, danach mindestens 5,0 °C",
        falsch=[
            "Maximal 18,0 °C, in den ersten 10 Lebenstagen mindestens 15,0 °C, danach mindestens 10,0 °C",
            "Maximal 30,0 °C, in den ersten 10 Lebenstagen mindestens 20,0 °C, danach mindestens 15,0 °C",
            "Maximal 12,0 °C, gleichmäßig über die gesamte Aufzucht",
        ],
        hinweis="Die relative Luftfeuchte im Aufenthaltsbereich liegt zwischen 60 und 80 %.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 6 Stallklima",
    ),
    dict(
        id="T2020.1", section="1", topic="Enthornung",
        frage="Bis zu welchem Alter darf ein Kalb nach § 5 Abs. 3 Nr. 2 Tierschutzgesetz ohne Betäubung enthornt werden?",
        antwort="Nur in den ersten 6 Lebenswochen",
        falsch=["Nur in den ersten 2 Lebenswochen", "Nur in den ersten 4 Lebenswochen", "Bis zum 3. Lebensmonat"],
        hinweis="Ab der 7. Woche ist die Betäubung zwingend; in der ökologischen Landwirtschaft ist in jedem Alter ein Tierarzt nötig.",
        quelle="Achselschwang/Enthornen.Kälber.pdf, Folie 4",
    ),
    dict(
        id="T2023.2", section="1", topic="Boxmaße",
        frage="Welche Mindestmaße (Länge × Breite × Höhe, innen) muss die Box für Kälber bis zu zwei Wochen haben?",
        antwort="120 cm × 80 cm × 80 cm",
        falsch=["100 cm × 70 cm × 70 cm", "150 cm × 90 cm × 90 cm", "160 cm × 100 cm × 100 cm"],
        hinweis="Die Boxmaße für Kälber über 2 bis 8 Wochen liegen mit 160 cm × 100 cm (Trog außen) deutlich höher.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 2 Haltungsanforderungen",
    ),
    dict(
        id="T2021.2", section="1", topic="Spaltenboden",
        frage="Wie breit darf die Spalte eines Spaltenbodens in der Kälberhaltung höchstens sein?",
        antwort="2,5 cm – bei elastisch ummantelten Spalten 3,0 cm",
        falsch=["1,0 cm – bei elastisch ummantelten Spalten 1,5 cm", "3,5 cm – bei elastisch ummantelten Spalten 4,0 cm", "5,0 cm – bei elastisch ummantelten Spalten 6,0 cm"],
        hinweis="Die Auftrittsbreite muss mindestens 8,0 cm betragen, zulässige Abweichung der Spaltenweite maximal 0,3 cm.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 1 Allgemeines",
    ),
    dict(
        id="T2020.2", section="1", topic="Beleuchtung",
        frage="Welche Anforderung stellt das Kälber-Merkblatt an die Beleuchtung im Aufenthaltsbereich?",
        antwort="Mindestens 10 Stunden täglich mindestens 80 Lux, dem Tagesrhythmus angeglichen",
        falsch=["Mindestens 6 Stunden täglich mindestens 50 Lux", "Mindestens 16 Stunden täglich mindestens 200 Lux", "Mindestens 8 Stunden täglich mindestens 100 Lux"],
        hinweis="Lichtöffnungen und Kunstlichtanlage sind nötig; für Altställe galt eine Frist zum 01.01.2008.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 5 Beleuchtung",
    ),
    dict(
        id="T2023.3", section="1", topic="Biestmilch",
        frage="Spätestens bis wann nach der Geburt muss Biestmilch angeboten werden?",
        antwort="Spätestens 4 Stunden nach der Geburt",
        falsch=["Spätestens 12 Stunden nach der Geburt", "Spätestens 24 Stunden nach der Geburt", "Spätestens 6 Stunden nach der Geburt"],
        hinweis="Innerhalb der ersten Lebensstunden sollten etwa 4 Liter Biestmilch verabreicht werden.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 3 Fütterung",
    ),
    dict(
        id="T2022.2", section="1", topic="Rauhfuttergabe",
        frage="Ab welchem Alter muss Rauhfutter für alle Kälber zur freien Aufnahme verfügbar sein?",
        antwort="Ab dem 8. Lebenstag",
        falsch=["Ab dem 1. Lebenstag", "Ab der 2. Lebenswoche", "Erst nach dem Absetzen von der Tränke"],
        hinweis="Silage oder die Kuhration während der Tränkeperiode zu verfüttern kann Durchfälle auslösen, daher empfiehlt die Gruber Tabelle Heu und Kraftfutter.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 3 Fütterung",
    ),
    dict(
        id="T2021.3", section="1", topic="Wasserversorgung",
        frage="Ab welchem Alter müssen Kälber jederzeit Zugang zu Wasser in ausreichender Menge und Qualität haben?",
        antwort="Ab einem Alter von 2 Wochen",
        falsch=["Ab der Geburt", "Ab einem Alter von 4 Wochen", "Erst ab der Entwöhnung"],
        hinweis="Wasser ist bereits für die Kälberentwicklung wichtig – es liefert auch Eisen für die Blutbildung.",
        quelle="rinderaufzucht/tierschutzanforderung_in_der_kaelberhaltung.pdf, Abschnitt 3 Fütterung",
    ),
    dict(
        id="T2020.3", section="1", topic="Tiertransport",
        frage="Wie lange darf ein Transport von Tieren grundsätzlich dauern?",
        antwort="Höchstens 8 Stunden",
        falsch=["Höchstens 4 Stunden", "Höchstens 6 Stunden", "Höchstens 12 Stunden"],
        hinweis="Für Kälber gilt ein Schema von maximal 9 Stunden, mindestens 1 Stunde Pause und maximal 9 Stunden weiterer Fahrt.",
        quelle="tiertransport und nottöten/Druckvorlage_Präsentation_Tierschutz_beim_Transport-AS-2025.pdf, S. 56",
    ),
    dict(
        id="T2022.3", section="1", topic="Nottötung",
        frage="Welche Aussage zum Bolzenschuss bei der Nottötung eines Rindes ist zutreffend?",
        antwort="Der Schuss wirkt betäubend; die Tötung muss direkt im Anschluss z. B. durch Entblutung erfolgen",
        falsch=[
            "Der Bolzenschuss wirkt nur betäubend und ersetzt die Tötung vollständig",
            "Der Bolzenschuss muss mindestens 10 Minuten einwirken, bevor entblutet wird",
            "Der Bolzenschuss wirkt auch bei ausgewachsenen Rindern zuverlässig und ist deshalb die Methode der Wahl",
        ],
        hinweis="Der Bolzenschuss wirkt über Gehirnerschütterung, mechanische Zerstörung von Gehirnarealen und einen Energieausfall im Schädelinneren.",
        quelle="tiertransport und nottöten/TVT-MB_75_Anh._1_Nottötung_Rind-Bolzenschuss_Feb._2018.pdf, S. 2–3",
    ),
    dict(
        id="T2023.4", section="1", topic="Krankheitserkennung",
        frage="Woran erkennen Sie im Stall, dass ein Kalb krank ist?",
        antwort="Am nicht aufgeweckten, desinteressierten Verhalten und an Säu- bzw. Fressunlust",
        falsch=[
            "Am ständigen Lautschrei und starker Bewegungsunruhe",
            "Am gezielten Meiden des Artgenossen und allein stehenden Kalbes",
            "Am erhöhten Fell- und Hautzustand mit sichtbarer Verletzung",
        ],
        hinweis="Das frühzeitige Erkennen von Krankheiten reduziert Kälberverluste während der Aufzuchtphase.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 1.2 (Musterlösung)",
    ),
    dict(
        id="T2021.4", section="1", topic="Hitzestress",
        frage="Woran äußert sich Hitzestress in einer Kuhherde im Sommer?",
        antwort="Durch allgemeine Unruhe, schnelle Atemfrequenz, verminderte Futteraufnahme sowie verringerte Milchleistung und Fruchtbarkeit",
        falsch=[
            "Durch starkes Fallen der Körpertemperatur unter 30 °C und Muskelzittern",
            "Durch verminderte Wasseraufnahme und erhöhte Trinkgeschwindigkeit bei gleichzeitig sinkender Atemfrequenz",
            "Durch ein deutlich gesteigertes Liegeverhalten und vermehrtes Wiederkauen",
        ],
        hinweis="Im Sommer sind die Liegezeiten meist kürzer – die Tiere suchen Schatten und kühle Flächen auf.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Milchviehhaltung 1.3 (Musterlösung)",
    ),
    # ---------------- 2. Tiere füttern ----------------
    dict(
        id="T2023.5", section="2", topic="Grundfutter",
        frage="Woran ist im Rahmen der deutschen DLG-Einteilung erkennbar, ob ein Futtermittel als Grundfutter gilt?",
        antwort="Am Energiegehalt von mehr als 7,0 MJ NEL/kg Trockensubstanz",
        falsch=["Am Rohproteingehalt von mehr als 20 %", "Am Rohfasergehalt von weniger als 10 %", "Am Trockensubstanzgehalt von mehr als 88 %"],
        hinweis="Futtermittel unter 7,0 MJ NEL/kg TM gelten als Kraftfutter.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/BILA_Tier_MV_Gl_4_5_Futtermittelkunde.pdf, Folie 3",
    ),
    dict(
        id="T2021.5", section="2", topic="Trockensubstanz",
        frage="Ein Futtermittel enthält weniger als 25 % Trockensubstanz. Was folgt daraus für den Wassergehalt?",
        antwort="Der Wassergehalt beträgt mehr als 75 %",
        falsch=["Der Wassergehalt beträgt weniger als 25 %", "Der Wassergehalt beträgt etwa 50 %", "Der Wassergehalt beträgt mehr als 90 %"],
        hinweis="Bei mehr als 25 % Trockensubstanz liegt der Wassergehalt entsprechend unter 75 %.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/BILA_Tier_MV_Gl_4_5_Futtermittelkunde.pdf, Folie 3",
    ),
    dict(
        id="T2022.4", section="2", topic="Energiestufen",
        frage="Welchen Energiegehalt in der Frischmasse muss ein Milchleistungsfutter der Energiestufe E 3 mindestens aufweisen?",
        antwort="6,7 MJ NEL",
        falsch=["6,2 MJ NEL", "7,2 MJ NEL", "7,0 MJ NEL"],
        hinweis="E 2 verlangt 6,2 MJ NEL, E 4 mindestens 7,0 MJ NEL; Milchleistungsfutter hat 18 % Rohprotein.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/BILA_Tier_MV_Gl_4_5_Futtermittelkunde.pdf, Folie 3",
    ),
    dict(
        id="T2020.4", section="2", topic="Weender Analyse",
        frage="Eine Futterprobe enthält 19,1 g Stickstoff je kg Trockensubstanz. Wie hoch ist der Rohproteingehalt?",
        antwort="Rund 119 g/kg TM, also 11,9 % Rohprotein (19,1 g N × 6,25)",
        falsch=["Rund 122 g/kg TM, also 12,2 % Rohprotein (19,1 g N × 6,38)", "Rund 19 g/kg TM, also 1,9 % Rohprotein", "Rund 244 g/kg TM, also 24,4 % Rohprotein (19,1 g N × 12,75)"],
        hinweis="Rohprotein wird aus dem Stickstoffgehalt berechnet: XP in g = 6,25 × N in g. Der Faktor 6,38 gilt für das Eiweiß der Milch.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/BILA_Tier_MV_Gl_4_5_Futtermittelkunde.pdf, Folie 6",
    ),
    dict(
        id="T2021.6", section="2", topic="Rohasche",
        frage="Welche Folge hat ein erhöhter Rohaschegehalt in einer Grassilage?",
        antwort="Er weist auf Futterverschmutzung mit Erde und Sand hin; der Energiegehalt sinkt und die Silierung wird schlechter",
        falsch=[
            "Er erhöht den Rohproteingehalt und damit die Eiweißqualität der Silage",
            "Er senkt den pH-Wert und verbessert die Gärqualität der Silage",
            "Er erhöht den Rohfasergehalt und verbessert die Pansenpassierbarkeit",
        ],
        hinweis="Als Zielwert für Grassilage wird ein Rohaschegehalt von unter 10 % genannt.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/BILA_Tier_MV_Gl_4_5_Futtermittelkunde.pdf, Folie 6",
    ),
    dict(
        id="T2022.5", section="2", topic="Gärqualität",
        frage="Welchen pH-Wert sollte eine gut silierte Grassilage im Zielbereich aufweisen?",
        antwort="4,0 bis 4,8",
        falsch=["6,5 bis 7,0", "3,0 bis 3,2", "5,5 bis 6,0"],
        hinweis="Je niedriger der Trockensubstanzgehalt ist, desto niedriger sollte der pH-Wert sein; bei Maissilage wird ein pH-Wert unter 4,2 empfohlen.",
        quelle="gruber_tabelle_milchvieh-2024_lfl-information.pdf, S. 102, Tab. 72",
    ),
    dict(
        id="T2020.5", section="2", topic="Silagebeurteilung",
        frage="Welche Gärsäure weist auf eine schlechte Silierung mit Clostridien hin und sollte in der Ration vermieden werden?",
        antwort="Buttersäure – Silagen sollten weniger als 3 g Buttersäure je kg Trockensubstanz enthalten",
        falsch=["Milchsäure – Silagen sollten weniger als 3 g Milchsäure je kg TM enthalten", "Essigsäure – Silagen sollten weniger als 3 g Essigsäure je kg TM enthalten", "Propionsäure – Silagen sollten weniger als 3 g Propionsäure je kg TM enthalten"],
        hinweis="Erwünscht sind 20–30 g Essigsäure und mehr als 50 g Milchsäure je kg TM; hohe Ammoniak-N-Gehalte über 8 % weisen auf Fehlgärung hin.",
        quelle="gruber_tabelle_milchvieh-2024_lfl-information.pdf, S. 100–101",
    ),
    dict(
        id="T2021.7", section="2", topic="Wasserbedarf",
        frage="Wie viel Wasser benötigt eine trockenstehende Kuh bei 25 °C Umgebungstemperatur pro Tag ungefähr?",
        antwort="Etwa 70 Liter",
        falsch=["Etwa 40 Liter", "Etwa 89 Liter", "Etwa 113 Liter"],
        hinweis="89 Liter werden bei 15 kg Milchleistung und 25 °C benötigt, 113 Liter bei 35 kg Milchleistung.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/BILA_Tier_MV_Gl_4_5_Futtermittelkunde.pdf, Folie 31",
    ),
    dict(
        id="T2023.6", section="2", topic="Tränkeplan",
        frage="Wieviel Tränke nimmt ein Kalb in der ersten, zweiten und dritten Lebenswoche bei ad-libitum-Fütterung ungefähr auf?",
        antwort="Ca. 8 l in Woche 1, ca. 10 l in Woche 2, ca. 12–14 l in Woche 3",
        falsch=["Ca. 2 l, ca. 4 l und ca. 6 l", "Ca. 4 l, ca. 6 l und ca. 8 l", "Ca. 12 l, ca. 15 l und ca. 18 l"],
        hinweis="Ab der fünften Lebenswoche wird kontinuierlich von zehn auf null Liter bis zur 12. Woche abgetränkt.",
        quelle="gruber_tabelle_milchvieh-2024_lfl-information.pdf, S. 14",
    ),
    dict(
        id="T2020.6", section="2", topic="Tränketemperatur",
        frage="Warum wird beim Anrühren eines Milchaustauschers eine höhere Temperatur als bei der Tränke verwendet?",
        antwort="Weil bei höherer Temperatur das zugesetzte Fett besser in Lösung geht – die Fetttröpfchen werden kleiner und damit besser verdaulich",
        falsch=[
            "Weil bei höherer Temperatur die Ansäuerung der Tränke entfällt",
            "Weil bei höherer Temperatur mehr Sauerstoff in der Tränke gelöst wird",
            "Weil bei höherer Temperatur das Casein schneller gerinnt und dadurch der Durchfall sinkt",
        ],
        hinweis="Bei der klassischen Warmtränke wird auf 41–42 °C erwärmt und dann auf Tränketemperatur von etwa 37 °C abgekühlt.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 2.5 (Musterlösung)",
    ),
    dict(
        id="T2022.6", section="2", topic="Pansenacidose",
        frage="Ab welchem pH-Wert im Pansen spricht man von einer Pansenacidose?",
        antwort="Unter 6,5",
        falsch=["Unter 5,0", "Unter 7,5", "Über 6,5"],
        hinweis="Zu viele schnell verdauliche Kohlenhydrate und zu wenig Faser senken die Wiederkauaktivität und die Speichelbildung – der pH-Wert fällt.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Milchviehhaltung 3.2 (Musterlösung)",
    ),
    # ---------------- 3. Tiere züchten ----------------
    dict(
        id="T2021.8", section="3", topic="Zyklusdauer",
        frage="Wie lange dauert der Brunstzyklus beim Rind im Durchschnitt?",
        antwort="21 Tage",
        falsch=["14 Tage", "18 Tage", "28 Tage"],
        hinweis="Der Zyklus gliedert sich in Vorbrunst, Hauptbrunst und Nachbrunst; die Eiblasung erfolgt etwa 2 Tage nach Brunstbeginn.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 12",
    ),
    dict(
        id="T2020.7", section="3", topic="Tragzeit",
        frage="Welche Trächtigkeitsdauer wird beim Fleckvieh als Zielwert angesetzt?",
        antwort="288 Tage",
        falsch=["281 Tage", "291 Tage", "114 Tage"],
        hinweis="Holstein-Friesian 281 Tage, Braunvieh 291 Tage; die Jungviehaufzucht-Folie nennt pauschal 285 Tage.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 53",
    ),
    dict(
        id="T2022.7", section="3", topic="Brunstmerkmale",
        frage="Welches Merkmal kennzeichnet die Hauptbrunst beim Rind am zuverlässigsten?",
        antwort="Der Duldungsreflex – die Kuh steht und lässt sich bespringen",
        falsch=["Der Ausfluss von klarem, fadenziehendem Schleim", "Die geschwollene, gerötete und warme Scham", "Die erhöhte Lauf- und Bewegungsaktivität"],
        hinweis="Die Merkmale treten in unterschiedlichen Phasen auf: In der Vorbrunst ist der Schleim dünn und wässrig, in der Nachbrunst trüb und pappig.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 22",
    ),
    dict(
        id="T2020.8", section="3", topic="Hormone",
        frage="Welches Hormon bewirkt die Auflösung des Gelbkörpers und damit das Ende der Trächtigkeit?",
        antwort="Prostaglandin (PGF2α)",
        falsch=["Progesteron", "Luteinisierendes Hormon (LH)", "Östradiol"],
        hinweis="Progesteron erhält die Trächtigkeit und hemmt GnRH, FSH und LH; LH löst den Eisprung aus.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 15",
    ),
    dict(
        id="T2021.9", section="3", topic="Trächtigkeitskontrolle",
        frage="Ab welchem Tag nach der Besamung kann eine Trächtigkeit rektal per Hand zuverlässig festgestellt werden?",
        antwort="Ab dem 42. Tag",
        falsch=["Ab dem 20. Tag", "Ab dem 28. Tag", "Ab dem 35. Tag"],
        hinweis="Der Milch-Progesteron-Test ist schon ab dem 20. Tag möglich, Ultraschall beziehungsweise der Milch-PAG-Test ab dem 28. Tag.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 49",
    ),
    dict(
        id="T2022.8", section="3", topic="Rastzeit",
        frage="Welchen Zielwert nennt das Fruchtbarkeitsmodul für die Rastzeit, also vom Abkalben bis zur ersten Besamung?",
        antwort="Unter 70 Tagen, im Optimalfall 50 bis 60 Tage",
        falsch=["Unter 30 Tagen", "Unter 100 Tagen", "Genau 42 Tage"],
        hinweis="Die Ruhezeit – Zeitraum zwischen Abkalbung und erster Brunst – hat dagegen einen Zielwert von 42 Tagen.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 52",
    ),
    dict(
        id="T2020.9", section="3", topic="Zuchtreife",
        frage="Woran beurteilen Sie, ob eine Kalbin zuchtreif zur ersten Belegung ist?",
        antwort="Sie erreicht etwa 60 % des Lebendgewichts der späteren Kuh, also 350–450 kg",
        falsch=["Sie erreicht 50 % des Endgewichts, also rund 210 kg", "Sie erreicht 80 % des Endgewichts, also rund 550 kg", "Sie erreicht das volle Endgewicht von 700–750 kg"],
        hinweis="Praktische Alternativen: Waage mit 58 % des Endgewichts, Brustumfang mindestens 175 cm oder Kreuzbeinhöhe von etwa 133 cm.",
        quelle="rinderaufzucht/4.2 Jungviehaufzucht.pdf, Folie 33 und 35",
    ),
    dict(
        id="T2021.10", section="3", topic="Brunstkontrolle",
        frage="Wie hoch ist der Anteil erkannter Brünste, wenn viermal täglich eine Brunstkontrolle durchgeführt wird?",
        antwort="100 %",
        falsch=["61 %", "80 %", "91 %"],
        hinweis="Eine Kontrolle einmal täglich erkennt 61 % der Brünste, zweimal 80 % und dreimal täglich 91 %.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 28",
    ),
    dict(
        id="T2022.9", section="3", topic="Brunststörungen",
        frage="Bei einer Kuh ist die Eierstocktätigkeit normal, die Brunstsymptome sind dauerhaft vorhanden. Wie heißt dieses Krankheitsbild?",
        antwort="Dauerbrunst (Nymphomanie)",
        falsch=["Stille Brunst (Anaphrodisie)", "Brunstlosigkeit (Azyklie)", "Zystisches Ovar mit stummem Brunstgeschehen"],
        hinweis="Ursache der Dauerbrunst ist unter anderem eine dünnwandige Thekazyste (Follikelzyste); bei der stillen Brunst ist die Eierstocktätigkeit dagegen normal, aber ohne Brunstsymptome.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 48",
    ),
    dict(
        id="T2020.10", section="3", topic="Abgangsursachen",
        frage="Welche Abgangsursache ist laut LKV-Jahresbericht 2021 bei Fleckvieh-Milchkühen am häufigsten?",
        antwort="Unfruchtbarkeit mit 21,4 %",
        falsch=["Sonstige Ursachen mit 28,2 %", "Euterkrankheit mit 16,6 %", "Geringe Leistung mit 10,6 %"],
        hinweis="Unfruchtbarkeit führt bei allen drei erfassten Rassen – bei Braunvieh mit 23,7 % und bei Schwarzbunten mit 18,8 % – die Liste der benannten Abgangsursachen an.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 5",
    ),
    # ---------------- 4. Schwerpunkt Milchviehhaltung ----------------
    dict(
        id="T2023.7", section="4", topic="Rohfaserbedarf",
        frage="Welchen Rohfasergehalt sollte die Ration einer Hochleistungskuh mindestens aufweisen?",
        antwort="Größer als 16 % der Trockensubstanz",
        falsch=["Größer als 12 % der Trockensubstanz", "Exakt 14 % der Trockensubstanz", "Kleiner als 10 % der Trockensubstanz"],
        hinweis="Eine Ration mit 14,2 % Rohfaser wurde in der Prüfung als zu niedrig bewertet.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Milchviehhaltung 4.1/4.2 (Musterlösung)",
    ),
    dict(
        id="T2023.8", section="4", topic="Rohfaserberechnung",
        frage="Eine Ration enthält 3.174,9 g Rohfaser bei einem Trockensubstanzgehalt der Ration von 22,25 kg. Wie hoch ist der Rohfasergehalt in Prozent?",
        antwort="Rund 14,2 % Rohfaser in der Trockensubstanz",
        falsch=["Rund 11,3 % Rohfaser in der Trockensubstanz", "Rund 18,6 % Rohfaser in der Trockensubstanz", "Rund 7,1 % Rohfaser in der Trockensubstanz"],
        hinweis="Rechnung: 3.174,9 g / 22,25 kg TM = 142,69 g Rohfaser je kg TM; 142,68 g / 1.000 g = 14,2 %.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Milchviehhaltung 4.1 (Musterlösung)",
    ),
    dict(
        id="T2023.9", section="4", topic="Liegezeit",
        frage="Eine Milchkuh soll täglich 12–14 Stunden liegen. Nennen Sie den wichtigsten Nutzen für die Milchbildung.",
        antwort="Das Liegen entlastet und durchblutet die Klauen und führt zu einem intensiveren Wiederkauen",
        falsch=["Das Liegen erhöht die Futteraufnahme und damit die Rohproteinversorgung", "Das Liehen senkt den Blutdruck und entlastet das Euter", "Das Liegen ersetzt das Ausmelken und reduziert die Melkzeit"],
        hinweis="Klauen trocknen im Liegen besser ab; die längere Ruhezeit erhöht die Wiederkauaktivität und damit die Futteraufnahme.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Milchviehhaltung 1.1 (Musterlösung)",
    ),
    dict(
        id="T2022.10", section="4", topic="Geburtshilfe",
        frage="Welche ist die größte Gefahr einer Hinterendlage für das Kalb?",
        antwort="Erstickungsgefahr, weil die Atmung einsetzt, bevor die Atemwege freiliegen",
        falsch=["Verletzung der Uteruswand durch dasBecken des Kalbes", "Verlust des Kolostrums durch zu frühes Absetzen der Mutter", "Starke Blutung der Kuh durch die Nabelschnur"],
        hinweis="Beim frühzeitigen Eintritt des Kalbbeckens in den Geburtskanal kann es zum Abquetschen oder Abreißen der Nabelschnur kommen, während der Kopf noch im Mutterleib liegt.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Milchviehhaltung 2.1 (Musterlösung)",
    ),
    dict(
        id="T2021.11", section="4", topic="Geburtslagen",
        frage="Welche Geburtslage und Stellung ist beim Rind die häufigste und damit unauffällige?",
        antwort="Vorderendlage in oberer Stellung in gestreckter Haltung – bei Färsen 84,8 %, bei Kühen 85,4 %",
        falsch=["Hinterendlage in oberer Stellung in gestreckter Haltung – bei Färsen 11,4 %", "Vorderendlage in unterer Stellung – bei Färsen über 80 %", "Andere Lage-, Stellungs- oder Haltungsanomalien – bei Färsen 3,8 %"],
        hinweis="Etwa 10–12 % der Einlingskälber kommen in Hinterendlage zur Welt, rund 15 % weichen von der Standardposition ab.",
        quelle="rinderaufzucht/DLG-Merkblatt_374.pdf, S. 16, Tabelle 3",
    ),
    dict(
        id="T2020.11", section="4", topic="Kalbverlauf",
        frage="Wie wird eine Schwergeburt in HIT definiert?",
        antwort="Geburtshilfe von mehr als einer Person oder mit einem mechanischen Geburtshelfer war nötig",
        falsch=["Geburtshilfe durch genau eine Person war nötig", "Die Kalbung dauerte länger als 24 Stunden", "Die Nachgeburt blieb zurück und musste entfernt werden"],
        hinweis="Leichtgeburt bedeutet keine Geburtshilfe, Normalgeburt Geburtshilfe durch eine Person; Kaiserschnitt und Embryotomie sind eigene Kategorien.",
        quelle="rinderaufzucht/BILA_JV_Geburt.pdf, Folie 22",
    ),
    dict(
        id="T2022.11", section="4", topic="Biestmilchqualität",
        frage="Welchen Brixwert sollte eingefrorene Biestmilch mindestens aufweisen?",
        antwort="Über 23, beim Einfrieren besser 26",
        falsch=["Über 10, beim Einfrieren besser 12", "Über 30, beim Einfrieren besser 35", "Über 15, beim Einfrieren besser 18"],
        hinweis="Die Qualität wird mit Kolostro- oder Refraktometer geprüft; bei Saugschwäche darf und soll gedrencht werden.",
        quelle="rinderaufzucht/BILA_JV_Geburt.pdf, Folie 16",
    ),
    dict(
        id="T2021.12", section="4", topic="Rohmilchgüte",
        frage="Welche Grenzwerte gelten nach der Rohmilchgüteverordnung für eine beanstandungsfreie Rohmilchprobe?",
        antwort="Gesamtkeimzahl bis 100.000 KBE/ml und somatische Zellzahl bis 400.000 Zellen/ml",
        falsch=["Gesamtkeimzahl bis 400.000 KBE/ml und somatische Zellzahl bis 100.000 Zellen/ml", "Gesamtkeimzahl bis 10.000 KBE/ml und somatische Zellzahl bis 100.000 Zellen/ml", "Gesamtkeimzahl bis 1.000.000 KBE/ml und somatische Zellzahl bis 1.000.000 Zellen/ml"],
        hinweis="Überschreitet eines dieser Merkmale, muss der Abnehmer den Erzeuger unterrichten; ein Hemmstoffnachweis wird gesondert behandelt.",
        quelle="Achselschwang/RohmilchGütV.pdf, § 23",
    ),
    dict(
        id="T2023.10", section="4", topic="Fruchtbarkeitseinflüsse",
        frage="Welcher Faktor hat nach den Angaben im Fruchtbarkeitsmodul den größten Einfluss auf die Fruchtbarkeit einer Herde?",
        antwort="Das Fruchtbarkeitsmanagement mit 40 %",
        falsch=["Die Fütterung mit 30 %", "Die Erblichkeit mit 15 %", "Haltung, Klima und Hygiene mit 10 %"],
        hinweis="Weitere Faktoren: Infektionen 5 %, Haltung/Klima/Hygiene 10 %, Erblichkeit 15 %, Fütterung 30 %, Fruchtbarkeitsmanagement 40 %.",
        quelle="4.1 BiLa_Bayern_Umdruck_Praesentation_Michviehhaltung_und_Vermarktung__Fruchtbarkeit_.pdf, Folie 59",
    ),
    # ---------------- 5. Schwerpunkt Kälber- und Jungviehhaltung ----------------
    dict(
        id="T2023.11", section="5", topic="Erstkalbealter",
        frage="Welches Erstkalbealter ist für Fleckvieh angestrebt?",
        antwort="26 bis 28 Monate",
        falsch=["18 bis 20 Monate", "32 bis 34 Monate", "40 bis 42 Monate"],
        hinweis="Bei Simmentaler liegt der Zielwert bei 24 bis 26 Monaten.",
        quelle="rinderaufzucht/4.2 Jungviehaufzucht.pdf, Folie 3",
    ),
    dict(
        id="T2022.12", section="5", topic="Erstkalbealterbewertung",
        frage="Ein Betrieb hat ein Erstkalbealter von 31 Monaten. Wie ist das zu bewerten?",
        antwort="Zu hoch – es liegt über dem Zielwert und über dem bayerischen Durchschnitt von 29 Monaten",
        falsch=["Zu niedrig – es liegt deutlich unter dem Zielwert", "Optimal – 31 Monate entsprechen genau dem Zielwert für Fleckvieh", "Unkritisch, weil das Erstkalbealter das Futteraufnahmevermögen nicht beeinflusst"],
        hinweis="Folgen sind hohe Aufzuchtkosten, mehr benötigte Stallplätze und ein erhöhtes Risiko für schwere Geburten und Ketose.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 3 (Musterlösung)",
    ),
    dict(
        id="T2021.13", section="5", topic="Jungviehfütterung",
        frage="Wie hoch ist der Energiebedarf eines Jungrindes mit 250 kg Lebendgewicht im Alter von 8 Monaten?",
        antwort="56 MJ ME pro Tag",
        falsch=["42 MJ ME pro Tag", "63 MJ ME pro Tag", "73 MJ ME pro Tag"],
        hinweis="Die Richtwerte gelten bei täglichen Zunahmen von 850 g im 1. und 700 g im 2. Aufzuchtjahr.",
        quelle="rinderaufzucht/4.2 Jungviehaufzucht.pdf, Folie 23",
    ),
    dict(
        id="T2020.12", section="5", topic="Körperkondition",
        frage="Welcher BCS-Wert ist bei Jungrindern als optimal anzustrebende Körperkondition angegeben?",
        antwort="3,5 auf der Skala von 1 bis 5",
        falsch=["2,0 auf der Skala von 1 bis 5", "2,75 auf der Skala von 1 bis 5", "4,5 auf der Skala von 1 bis 5"],
        hinweis="BCS 2,75 gilt als zu mager, BCS 4,5 als zu fett; die Körperkondition wird regelmäßig kontrolliert.",
        quelle="rinderaufzucht/4.2 Jungviehaufzucht.pdf, Folie 28",
    ),
    dict(
        id="T2022.13", section="5", topic="Kälberfütterung",
        frage="Wie hoch ist der Rohproteinbedarf eines Kalbes in der 1. bis 4. Lebenswoche?",
        antwort="Etwa 240 g Rohprotein pro Tag",
        falsch=["Etwa 120 g Rohprotein pro Tag", "Etwa 400 g Rohprotein pro Tag", "Etwa 60 g Rohprotein pro Tag"],
        hinweis="Kontrollrechnung der Prüfung: 8 l Tränke × 140 g MAT/l = 1.120 g MAT; 1.120 g × 22 % Rohprotein = 246,4 g – der Bedarf ist gedeckt.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 2.4 (Musterlösung)",
    ),
    dict(
        id="T2021.14", section="5", topic="Milchaustauscher",
        frage="Welchen Zielwert für den Rohproteingehalt eines Milchaustauschers nennt die Prüfung?",
        antwort="20 bis 22 % der Frischmasse",
        falsch=["12 bis 14 % der Frischmasse", "26 bis 28 % der Frischmasse", "30 bis 32 % der Frischmasse"],
        hinweis="Weitere Orientierungswerte: Rohasche maximal 8 %, Rohfett 16–20 % und Eisen mindestens 60 mg/kg.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 2.1 (Musterlösung)",
    ),
    dict(
        id="T2020.13", section="5", topic="Tränkemenge",
        frage="Sie wollen 24 Liter Tränke mit 140 g Milchaustauscher je Liter anrühren. Wie viel Wasser müssen Sie dazu verwenden?",
        antwort="20,64 Liter Wasser",
        falsch=["23,34 Liter Wasser", "21,36 Liter Wasser", "17,00 Liter Wasser"],
        hinweis="Rechnung: 24 l × 140 g/l = 3.360 g = 3,36 kg MAT; 24 l − 3,36 kg = 20,64 Liter Wasser.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 2.3 (Musterlösung)",
    ),
    dict(
        id="T2022.14", section="5", topic="Nullaustauscher",
        frage="Warum eignet sich ein Nullaustauscher nicht für junge Kälber bis zur 4. Lebenswoche?",
        antwort="Ihm fehlt hochwertiges tierisches Protein, und er enthält meist pflanzliche Proteine, die schlecht verdaulich sind",
        falsch=[
            "Ihm fehlt der Gehalt an Rohfett, wodurch die Verträglichkeit sinkt",
            "Er enthält zu viel Magermilchpulver und führt deshalb zu Durchfall",
            "Er ist nicht pelletiert und daher für Kälber mechanisch zu schwer",
        ],
        hinweis="Bis zur vierten Lebenswoche fehlen die nötigen Verdauungsenzyme für pflanzliches Protein; ein hoher Magermilchanteil ist daher entscheidend.",
        quelle="Prüfungsaufgabe Tierproduktion 2023, Schwerpunkt Kälber- und Jungviehhaltung 2.6 (Musterlösung)",
    ),
    # ---------------- 6. Schwerpunkt Ferkelerzeugung und Schweinemast ----------------
    dict(
        id="T2023.12", section="6", topic="Ferkelfutter",
        frage="Welchen ME-Gehalt sollte Ferkelfutter in der Phase Prestarter und Absetzfutter (5–12 kg Lebendmasse) aufweisen?",
        antwort="13,4 MJ ME je kg Futter",
        falsch=["12,0 MJ ME je kg Futter", "11,5 MJ ME je kg Futter", "14,5 MJ ME je kg Futter"],
        hinweis="Ab 20 kg Lebendmasse sinkt der Richtwert auf 13,2 MJ ME/kg.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 27",
    ),
    dict(
        id="T2022.15", section="6", topic="Aminosäuren",
        frage="Welches Verhältnis von Lysin zu Methionin+Cystein ist beim Mastschwein als Richtwert angegeben?",
        antwort="1 : 0,55",
        falsch=["1 : 0,25", "1 : 0,85", "1 : 1,50"],
        hinweis="Weitere Richtwerte im Futter: Threonin 0,65 und Tryptophan 0,18 je Lysin; das Verhältnis Ca : verfügbares P liegt bei 2,2–2,5 : 1.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 16",
    ),
    dict(
        id="T2021.15", section="6", topic="Zuchtsauenziele",
        frage="Welche Zielwerte nennt die Futterwerttabelle für die Zuchtsauenhaltung?",
        antwort="Über 12 lebend geborene Ferkel je Wurf, über 2,3 Würfe je Sau und Jahr und über 7,5 kg Absetzgewicht",
        falsch=["Über 8 lebend geborene Ferkel je Wurf, über 1,8 Würfe je Sau und Jahr und über 5,0 kg Absetzgewicht", "Über 16 lebend geborene Ferkel je Wurf, über 3,5 Würfe je Sau und Jahr und über 10 kg Absetzgewicht", "Über 10 lebend geborene Ferkel je Wurf, über 2,3 Würfe je Sau und Jahr und über 12 kg Absetzgewicht"],
        hinweis="Die Säugezeit sollte 28 Tage nicht überschreiten; angestrebt werden über 70 Ferkel je Sau und Lebensleistung.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 18",
    ),
    dict(
        id="T2020.14", section="6", topic="Jungsauenaufzucht",
        frage="In welchem Alter und mit welcher Lebendmasse sollte eine Jungsau zur ersten Belegung kommen?",
        antwort="Im Alter von 240 bis 260 Tagen bei 130 bis 150 kg Lebendmasse",
        falsch=["Im Alter von 180 bis 200 Tagen bei 90 bis 100 kg Lebendmasse", "Im Alter von 300 bis 320 Tagen bei 190 bis 210 kg Lebendmasse", "Im Alter von 120 bis 140 Tagen bei 70 bis 80 kg Lebendmasse"],
        hinweis="Die Erstbelegung erfolgt im 2. bis 3. Östrus, die Rückenspeckdicke bei der Besamung sollte 12–14 mm betragen.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 15",
    ),
    dict(
        id="T2022.16", section="6", topic="Thermoneutraler Bereich",
        frage="Welche Temperatur liegt im thermoneutralen Bereich für tragende Sauen bei Gruppenhaltung?",
        antwort="14 °C – je 1 °C darunter sind 0,3 MJ ME/Tag zusätzlich nötig",
        falsch=["19 °C – je 1 °C darunter sind 0,6 MJ ME/Tag zusätzlich nötig", "22 °C – je 1 °C darunter sind 0,3 MJ ME/Tag zusätzlich nötig", "8 °C – je 1 °C darunter sind 0,6 MJ ME/Tag zusätzlich nötig"],
        hinweis="Bei Einzelhaltung liegt der thermoneutrale Bereich bei 19 °C mit einem Zuschlag von 0,6 MJ ME/Tag je Grad Celsius.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 18",
    ),
    dict(
        id="T2021.16", section="6", topic="Ferkelentwicklung",
        frage="Welche Lebendmasse hat ein Ferkel am Ende seiner ersten Lebenswoche?",
        antwort="Etwa 2,8 kg",
        falsch=["Etwa 1,4 kg", "Etwa 4,3 kg", "Etwa 6,0 kg"],
        hinweis="Die Ferkel nehmen in der ersten Woche etwa 200 g pro Tag zu; 4,3 kg entsprechen dem Ende der zweiten Woche.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 27",
    ),
    dict(
        id="T2023.13", section="6", topic="Eberhaltung",
        frage="Welche Energiedichte sollte im Futter für Eber höchstens enthalten sein?",
        antwort="Höchstens 12,5 MJ ME je kg Futter",
        falsch=["Höchstens 10,0 MJ ME je kg Futter", "Höchstens 14,0 MJ ME je kg Futter", "Höchstens 16,0 MJ ME je kg Futter"],
        hinweis="Zielwerte der Eberaufzucht sind 140–180 kg Lebendmasse und 600–700 g Lebenstagszunahme; ad libitum-Fütterung bis 120 kg, danach restriktiv.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 17",
    ),
    dict(
        id="T2020.15", section="6", topic="Rohfaserbedarf",
        frage="Welchen Rohfasergehalt (XF) sollte Ferkelfutter in den einzelnen Fütterungsabschnitten haben?",
        antwort="40 g/kg ab dem Absetzfutter, 35 g/kg bei 12–20 kg und 30 g/kg bei 20–30 kg Lebendmasse",
        falsch=["10 g/kg in allen Abschnitten", "60 g/kg im Prestarter, sinkend auf 40 g/kg", "Keine Angabe, weil Schweine Rohfaser nicht verwerten können"],
        hinweis="Beim Absetzen (4. Woche) benötigt der Ferkel 100 g Futter pro Tag, in der 7. Woche bereits 830 g.",
        quelle="Grundlagen landwirtschaftlicher tierhaltung/futterwerttabelle_schwein_lfl-information.pdf, S. 27",
    ),
]
