SECTIONS = {
    "bw": "Betriebswirtschaft",
    "arbeitswirtschaft": "Arbeitswirtschaft",
    "recht": "Recht, Steuern, Verträge",
    "sozialkunde": "Sozialkunde",
}

QUESTIONS = [
    dict(
        id="W20.1",
        section="bw",
        topic="Abschreibung und Zins",
        frage="Sie kaufen einen 85-PS-Schlepper für 85.000 €. Die Nutzungsdauer beträgt 12 Jahre, der Restwert 30.000 €, der Zinssatz 4 %. Wie hoch sind Abschreibung und Zinsansatz pro Jahr?",
        antwort="Abschreibung 4.583,33 €/Jahr, Zinsansatz 2.300 €/Jahr",
        falsch=[
            "Abschreibung 7.083,33 €/Jahr, Zinsansatz 2.300 €/Jahr",
            "Abschreibung 4.583,33 €/Jahr, Zinsansatz 3.400 €/Jahr",
            "Abschreibung 2.500,00 €/Jahr, Zinsansatz 3.400 €/Jahr",
        ],
        hinweis="Abschreibung mit Restwert: (85.000 − 30.000) : 12 = 4.583,33 €/Jahr. Zinsansatz: (85.000 + 30.000) : 2 x 4 % = 2.300 €/Jahr.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 2 und S. 3",
    ),
    dict(
        id="W20.2",
        section="bw",
        topic="Maschinenkosten",
        frage="Für den 85er Schlepper (85.000 €) sind Abschreibung 4.583,33 €, Zinsansatz 2.300 € sowie je 0,5 % vom Anschaffungswert für Versicherung und Unterbringung (je 425 €) angesetzt. Die variablen Kosten liegen bei 17 €/h. Wie hoch sind die Gesamtkosten bei 800 Einsatzstunden im Jahr?",
        antwort="21.333 € je Jahr, das sind 26,67 €/h",
        falsch=[
            "13.600 € je Jahr, das sind 17,00 €/h",
            "17.933 € je Jahr, das sind 29,89 €/h",
            "20.783 € je Jahr, das sind 25,98 €/h",
        ],
        hinweis="Festkosten 4.583,33 + 2.300 + 425 + 425 = 7.733,33 €/Jahr. Bei 800 h: 7.733,33 + 800 x 17 = 21.333,33 €; je Stunde 21.333,33 : 800 = 26,67 €/h.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 3 und S. 4",
    ),
    dict(
        id="W20.3",
        section="bw",
        topic="Abschreibungsschwelle",
        frage="Ein Schlepper wird nach 10.000 Schlepperstunden oder nach 12 Jahren abgeschrieben. Ab welchem jährlichen Einsatzumfang ist die Nutzungsdauer durch den Verschleiß und nicht mehr durch das Alter begrenzt?",
        antwort="Ab mehr als rund 833 Schlepperstunden im Jahr",
        falsch=[
            "Ab mehr als rund 400 Schlepperstunden im Jahr",
            "Ab mehr als rund 1.200 Schlepperstunden im Jahr",
            "Nie – die Abschreibung ist grundsätzlich nutzungsunabhängig",
        ],
        hinweis="Der Grenzeinsatz liegt bei 10.000 Sh : 12 Jahre = 833 Schlepperstunden im Jahr. Darüber ist die Leistungsgrenze (10.000 Sh) früher erreicht, es muss dann nach Leistung abgeschrieben werden.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 4 und S. 5",
    ),
    dict(
        id="W20.4",
        section="bw",
        topic="Mähdrescher",
        frage="Ein Mähdrescher kostet 350.000 €, die Nutzungsdauer beträgt 12 Jahre ohne Restwert, der Zinssatz 4 %. Wie hoch sind Abschreibung und Zinsansatz pro Jahr?",
        antwort="Abschreibung 29.166,67 €, Zinsansatz 7.000 €",
        falsch=[
            "Abschreibung 29.166,67 €, Zinsansatz 14.000 €",
            "Abschreibung 23.333,33 €, Zinsansatz 7.000 €",
            "Abschreibung 29.166,67 €, Zinsansatz 3.500 €",
        ],
        hinweis="Ohne Restwert: 350.000 : 12 = 29.166,67 €/Jahr. Zins auf den halben Anschaffungswert: 350.000 : 2 x 4 % = 7.000 €/Jahr.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 6",
    ),
    dict(
        id="W20.5",
        section="bw",
        topic="Gebäudeunterhalt",
        frage="Wie hoch wird der jährliche Unterhaltsaufwand eines Gebäudes angesetzt, wenn der AfA-Grad 70 % beträgt?",
        antwort="1,5 % der Anschaffungskosten",
        falsch=[
            "0,5 % der Anschaffungskosten",
            "1,0 % der Anschaffungskosten",
            "2,0 % der Anschaffungskosten",
        ],
        hinweis="Richtwerte: unter 25 % AfA-Grad 0,5 %, 25 bis 60 % 1,0 %, 60 bis 75 % 1,5 %, über 75 % 2,0 % der Anschaffungskosten. 70 % liegt im Bereich 60 bis 75 %.",
        quelle="Skripte erste Blockwoche 2025/02_Produktionsfaktor Kapital-Gebäude TN_WM_2025.pdf, Folie 21",
    ),
    dict(
        id="W20.7",
        section="bw",
        topic="AfA-Grad",
        frage="Ein Stall wurde 2003 für 239.669 € angeschafft, die Nutzungsdauer beträgt 25 Jahre. Der Buchwert im Jahr 2018 liegt bei 95.864 €. Wie hoch ist der AfA-Grad?",
        antwort="60 %",
        falsch=[
            "40 %",
            "25 %",
            "80 %",
        ],
        hinweis="Kumulierte Abschreibung = 239.669 − 95.864 = 143.805 €. AfA-Grad = 143.805 : 239.669 x 100 = 60 %.",
        quelle="Skripte erste Blockwoche 2025/02_Produktionsfaktor Kapital-Gebäude TN_WM_2025.pdf, Folie 13 und Folie 14",
    ),
    dict(
        id="W20.8",
        section="bw",
        topic="Nutzungsdauer Stall",
        frage="Welche steuerliche Nutzungsdauer wird für Stallbauten angesetzt, wenn die tatsächliche Nutzungsdauer darüber liegt?",
        antwort="25 Jahre, die tatsächliche Nutzungsdauer kann bis zu 50 Jahre betragen",
        falsch=[
            "33 Jahre, die tatsächliche Nutzungsdauer liegt bei 50 Jahren",
            "50 Jahre – es wird die volle tatsächliche Nutzungsdauer angesetzt",
            "30 Jahre, wie es die Kalkulationsvorgaben der Landmaschinenringe vorsehen",
        ],
        hinweis="Für Stallbauten ist steuerlich eine Nutzungsdauer von 25 Jahren (4 %) angesetzt, tatsächlich können die Gebäude länger, bis zu 50 Jahre, genutzt werden. Maschinenhallen: 25 Jahre, Fahrsilos: 33 Jahre.",
        quelle="Skripte erste Blockwoche 2025/02_Produktionsfaktor Kapital-Gebäude TN_WM_2025.pdf, Folie 9",
    ),
    dict(
        id="W21.1",
        section="bw",
        topic="Gesamtdeckungsbeitrag",
        frage="Landwirt Lampl baut auf 5 ha Acker 1 ha Winterweizen (DB 650 €/ha), 2 ha Silomais (DB −1.478 €/ha) und 2 ha Kleegras (DB −1.100 €/ha) an. Die 20 ha Grünland werden mit 15 ha Grassilage (DB −953 €/ha) und 5 ha Heu (DB −1.008 €/ha) genutzt. Er hält 30 Milchkühe mit je 3.000 € DB und erzeugt 10 Kalbinnen zu je 1.300 €. Wie hoch ist der Gesamtdeckungsbeitrag des Betriebes?",
        antwort="79.159 €",
        falsch=[
            "91.159 €",
            "66.159 €",
            "103.650 €",
        ],
        hinweis="650 − 2 x 1.478 − 2 x 1.100 − 15 x 953 − 5 x 1.008 + 30 x 3.000 + 10 x 1.300 = 650 − 24.491 + 103.000 = 79.159 €.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 11",
    ),
    dict(
        id="W21.2",
        section="bw",
        topic="Gewinnberechnung",
        frage="Landwirt Lampl erhält 12.000 € Prämien pro Jahr, die jährlichen Festkosten am Gesamtbetrieb betragen 40.000 €. Wie hoch ist der Gewinn des Betriebes?",
        antwort="51.159 €",
        falsch=[
            "39.159 €",
            "63.650 €",
            "91.159 €",
        ],
        hinweis="Gesamtdeckungsbeitrag 79.159 € zuzüglich Prämien 12.000 € ergeben 91.159 €, davon 40.000 € Festkosten abgezogen ergibt 51.159 € Gewinn.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 10 und S. 11",
    ),
    dict(
        id="W21.3",
        section="bw",
        topic="Grundfutter-DB",
        frage="Der Deckungsbeitrag von Silomais beträgt −1.478 €/ha, weil die Leistung innerbetrieblich verwertet wird. Eine Biogasanlage zahlt 1.950 €/ha für Silomais. Wie verändert sich der Deckungsbeitrag durch den Verkauf?",
        antwort="Er wird positiv und beträgt +472 €/ha",
        falsch=[
            "Er bleibt negativ und beträgt weiterhin −1.478 €/ha",
            "Er wird positiv und beträgt +1.950 €/ha",
            "Er wird negativ und beträgt −472 €/ha",
        ],
        hinweis="Beim Verkauf an die Biogasanlage tritt an die Stelle der innerbetrieblichen Futterlieferung eine Marktleistung: 1.950 − 1.478 = +472 €/ha.",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 9",
    ),
    dict(
        id="W21.4",
        section="bw",
        topic="NEL-Kosten",
        frage="Bei welchem Grundfutterverfahren sind die variablen Kosten je 10 MJ NEL am höchsten?",
        antwort="Bei Grassilage mit 19,87 ct je 10 MJ NEL",
        falsch=[
            "Bei Heu mit 17,25 ct je 10 MJ NEL",
            "Bei Silomais mit 13,4 ct je 10 MJ NEL",
            "Bei Grassilage mit 17,25 ct je 10 MJ NEL",
        ],
        hinweis="Die Grundfutterverfahren liefern 50.400 MJ NEL/ha bei Grassilage (953 €/ha variable Kosten), 110.300 MJ bei Silomais (1.478 €/ha) und 34.500 MJ bei Heu (1.008 €/ha).",
        quelle="Wiederholung Grundlagen_Schnürch_26.pdf, S. 9",
    ),
    dict(
        id="W21.5",
        section="bw",
        topic="Standard-DB",
        frage="Welche Voraussetzung muss erfüllt sein, damit der eigene Deckungsbeitrag für den überbetrieblichen Vergleich herangezogen werden kann?",
        antwort="Man rechnet den DB nach einer vorgegebenen, einheitlichen Systematik mit durchschnittlichen Marktleistungen und variablen Kosten für Betriebe mit gleichem Betriebssystem",
        falsch=[
            "Der Betrieb muss die tatsächlichen Ist-Kosten und Ist-Erlöse seines Jahres verwenden",
            "Es genügt, wenn die Betriebe dieselben Kulturarten anbauen, unabhängig vom Standort",
            "Der DB muss für alle Produktionsverfahren eines Betriebes in einem Jahr errechnet werden",
        ],
        hinweis="Standard-Deckungsbeiträge werden für Betriebe mit gleichen Produktionsverfahren (gleichem Betriebssystem) gebildet; Standort, Können des Betriebsleiters und Rahmenbedingungen werden dadurch vereinheitlicht.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 51",
    ),
    dict(
        id="W22.1",
        section="bw",
        topic="Kostenabgrenzung",
        frage="Nach welchem Kriterium wird im Deckungsbeitrag abgegrenzt, ob eine Kostenposition variable oder Festkosten ist?",
        antwort="Kosten sind variabel, wenn sie bei Ausdehnung oder Einschränkung des Produktionsverfahrens proportional zum Produktionsumfang mitgehen und bei Verfahrensaufgabe wegfallen",
        falsch=[
            "Kosten sind variabel, wenn sie auch bei Aufgabe des Produktionsverfahrens weiter anfallen",
            "Kosten sind variabel, wenn sie über die gesamte Nutzungsdauer pauschal verteilt werden",
            "Kosten sind variabel, wenn sie ausschließlich an entlohnte Fremdkräfte gezahlt werden",
        ],
        hinweis="Maßgeblich ist die Proportionalität: Ändern sich die Kosten im gleichen Verhältnis wie der Produktionsumfang, sind sie variable Kosten. Abschreibungen, Versicherung und Unterhalt bleiben bei Verfahrensaufgabe bestehen, also Festkosten.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 8",
    ),
    dict(
        id="W22.2",
        section="bw",
        topic="Milcherlös",
        frage="Eine Kuh liefert 7.450 kg Milch im Jahr, der Milchpreis beträgt 0,5169 €/kg. Wie hoch ist der Milcherlös je Kuh und Jahr?",
        antwort="3.851 €",
        falsch=[
            "3.076 €",
            "5.315 €",
            "746 €",
        ],
        hinweis="Milcherlös = Milchpreis x verkaufte Milch = 0,5169 €/kg x 7.450 kg = 3.850,90 €, gerundet 3.851 €. Abzuziehen sind Tränkmilch, Zellmilch und Haushaltsmilch.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 19 und Folie 50",
    ),
    dict(
        id="W22.3",
        section="bw",
        topic="Altkuherlös",
        frage="Eine Altkuh wiegt 670 kg, die Ausschlachtung beträgt 53 %, der Schlachtpreis 7,00 €/kg. Wie hoch ist der Altkuherlös bei einer Abgangsquote von 30 %?",
        antwort="746 €",
        falsch=[
            "2.486 €",
            "1.243 €",
            "1.740 €",
        ],
        hinweis="Wert der Altkuh = 670 kg x 0,53 x 7,00 €/kg = 2.486 €; Altkuherlös = 2.486 € x 30 % Abgangsquote = 745,80 €, gerundet 746 €.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 21 und Folie 25",
    ),
    dict(
        id="W22.4",
        section="bw",
        topic="Kälbererlös",
        frage="Die durchschnittliche Zwischenkalbezeit beträgt 393 Tage, die Kälberverluste 10 %. Bullenkälber kosten 900 €, Kuhkälber 534 €, das Geschlechterverhältnis ist 50 : 50. Wie hoch ist der Kälbererlös je Kuh und Jahr?",
        antwort="602 €",
        falsch=[
            "717 €",
            "1.434 €",
            "534 €",
        ],
        hinweis="Kalbungen je Jahr = 365 : 393 = 0,93; nach Verlusten 0,93 : 1,1 = 0,84 Kälber. Mischpreis (0,42 x 900) + (0,42 x 534) = 602 €.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 29",
    ),
    dict(
        id="W22.5",
        section="bw",
        topic="Kälberaufzucht",
        frage="Welche Aufzuchtkosten fallen für ein Kalb bei 8 Wochen Tränkedauer an (Vollmilch 48 kg zu 0,32 €/kg, MAT 37 kg zu 2,52 €/kg, Kälberstarter 29,5 kg zu 0,40 €/kg)?",
        antwort="120,46 € je Kalb",
        falsch=[
            "108,66 € je Kalb",
            "93,24 € je Kalb",
            "15,42 € je Kalb",
        ],
        hinweis="Vollmilch 48 x 0,32 = 15,42 €; MAT 37 x 2,52 = 93,24 €; Kälberstarter 29,5 x 0,40 = 11,80 €. Summe = 120,46 €.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 37",
    ),
    dict(
        id="W22.6",
        section="bw",
        topic="DB Milchkuh",
        frage="Eine Kuh bringt 5.315 € Leistungen (davon 5.199 € Marktleistung und 116 € Wirtschaftsdünger) und 1.995 € variable Kosten. Wie hoch ist der Deckungsbeitrag I je Kuh und Jahr?",
        antwort="3.320 €",
        falsch=[
            "5.315 €",
            "3.204 €",
            "1.995 €",
        ],
        hinweis="Deckungsbeitrag I = Summe der Leistungen − Summe der variablen Kosten = 5.315 − 1.995 = 3.320 €. Der Wirtschaftsdünger gehört zur Leistung, die Bestandsergänzung von 540 € dagegen zu den variablen Kosten.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 50",
    ),
    dict(
        id="W22.7",
        section="arbeitswirtschaft",
        topic="AK-Besatz",
        frage="Wie vielen Arbeitskraftstunden entspricht eine Arbeitskrafteinheit?",
        antwort="Einer nicht entlohnten Familien-AK 2.300 AKh, einer entlohnten Fremd-AK 1.800 AKh",
        falsch=[
            "Beide werden mit 2.300 AKh angesetzt",
            "Familien-AK 1.800 AKh, Fremd-AK 2.300 AKh",
            "Beide werden mit 1.800 AKh angesetzt",
        ],
        hinweis="Für die nicht entlohnten Familien-Arbeitskräfte werden 2.300 AKh je AK angesetzt, für entlohnte Fremd-Arbeitskräfte 1.800 AKh.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 2",
    ),
    dict(
        id="W22.9",
        section="arbeitswirtschaft",
        topic="AK-Berechnung",
        frage="Betriebsleiter 54 Jahre (2.300 AKh), Ehegatte 49 Jahre mit 20 h/Woche Schule und 3 h täglich Haushalt, Hofnachfolger 20 Jahre mit 500 h/Jahr MR-Arbeit, Altenteiler 79 Jahre und ein Angestellter halbtags. Wie hoch ist der gesamte AK-Besatz?",
        antwort="2,54 AK, das sind 5.855 AKh",
        falsch=[
            "2,14 AK, das sind 4.922 AKh",
            "2,00 AK, das sind 4.600 AKh",
            "3,54 AK, das sind 8.142 AKh",
        ],
        hinweis="Ehegatte: 20 x 52 = 1.040 AKh plus 3 x 365 = 1.095 AKh, also 2.135 AKh; bleiben 2.300 − 2.135 = 165 AKh. Hofnachfolger 2.300 − 500 = 1.800 AKh. Altenteiler 0,3 x 2.300 = 690 AKh. Angestellter 1.800 x 0,5 = 900 AKh. Summe 5.855 AKh = 2,54 AK.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 4",
    ),
    dict(
        id="W22.10",
        section="arbeitswirtschaft",
        topic="Arbeitszeitbedarf",
        frage="Ein Betrieb mit 60 ha LF braucht laut Richtwerten 680 AKh Außenwirtschaft, 3.100 AKh Viehhaltung, 40 AKh Waldarbeit und 480 AKh für Betriebsführung und Hofarbeiten. Wie viele Arbeitskrafteinheiten entspricht das?",
        antwort="1,87 AK, weil 4.300 AKh : 2.300 AKh je AK ergeben 1,87",
        falsch=[
            "2,39 AK, weil mit 1.800 AKh je Fremd-AK gerechnet wird",
            "1,00 AK, weil 4.300 AKh gerade eine Arbeitskrafteinheit sind",
            "4,30 AK, weil je Hektar eine AKh gerechnet wird",
        ],
        hinweis="Gesamter Arbeitszeitbedarf 680 + 3.100 + 40 + 480 = 4.300 AKh. Umrechnung auf Familien-AK: 4.300 : 2.300 = 1,87 AK.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 8",
    ),
    dict(
        id="W22.11",
        section="arbeitswirtschaft",
        topic="Lohnansatz",
        frage="Worin unterscheidet sich der Lohnansatz von den Lohnkosten?",
        antwort="Der Lohnansatz ist eine Rechengröße für die nicht entlohnten Familien-AK; es gibt keine tatsächlichen Zahlungsströme, er dient dem Vergleich",
        falsch=[
            "Der Lohnansatz wird nur für entlohnte Fremd-AK angesetzt und ist eine tatsächliche Auszahlung",
            "Lohnansatz und Lohnkosten sind dieselbe Größe, beide werden tatsächlich gezahlt",
            "Der Lohnansatz ist eine steuerliche Pauschale, die das Finanzamt festsetzt",
        ],
        hinweis="Lohnkosten sind Geld- und Sachleistungen für entlohnte AK und beim Gewinn bereits abgezogen; der Lohnansatz ist ein rechnerischer Wert ohne Zahlungsstrom, mit dem die theoretische Stundenentlohnung der Familienarbeit geprüft wird.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 6",
    ),
    dict(
        id="W22.13",
        section="arbeitswirtschaft",
        topic="Stundenentlohnung",
        frage="Ein Betrieb erzielt 80.000 € Gewinn und setzt 3.000 AKh ein. Wie hoch ist die theoretische Stundenentlohnung der Familienarbeit?",
        antwort="26,60 €/h",
        falsch=[
            "53,30 €/h",
            "80,00 €/h",
            "13,30 €/h",
        ],
        hinweis="80.000 € Gewinn : 3.000 AKh = 26,60 € theoretische Stundenentlohnung. Betriebswirtschaftlich muss dabei ein sinnvoller Stundenlohn herauskommen, damit das Unternehmen rentabel ist.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 6",
    ),
    dict(
        id="W22.14",
        section="arbeitswirtschaft",
        topic="Arbeitszeitrichtwerte",
        frage="Mit welchem Arbeitszeitbedarf wird im Richtwert für Spargel als Dauerkultur gerechnet?",
        antwort="1.400 bis 1.600 AKh je Hektar und Jahr",
        falsch=[
            "140 bis 160 AKh je Hektar und Jahr",
            "14 bis 16 AKh je Hektar und Jahr",
            "280 bis 330 AKh je Hektar und Jahr",
        ],
        hinweis="Die Richtwerte der Außenwirtschaft lauten: Getreide 6 bis 12, Silomais 10 bis 25, Grünland-Futterbau 10 bis 15, Wald 10 bis 25 AKh/ha; Hopfen 280 bis 330 und Spargel 1.400 bis 1.600 AKh/ha.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 7",
    ),
    dict(
        id="W22.15",
        section="arbeitswirtschaft",
        topic="Melkarbeitszeit",
        frage="Welche Arbeitskraftstunden werden je Milchkuh und Jahr für automatisches Melken und für das Standeimermelken angesetzt?",
        antwort="Automatisches Melksystem 30 bis 40 AKh, Standeimer 110 bis 130 AKh",
        falsch=[
            "Automatisches Melksystem 70 bis 85 AKh, Standeimer 30 bis 40 AKh",
            "Automatisches Melksystem 45 bis 60 AKh, Standeimer 110 bis 130 AKh",
            "Für beide Melkverfahren werden 45 bis 60 AKh je Kuh und Jahr angesetzt",
        ],
        hinweis="Innenwirtschaft: AMS 30 bis 40, Melkstand 45 bis 60, Rohrmelkanlage 70 bis 85, Standeimer 110 bis 130 AKh je Milchkuh und Jahr.",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 7",
    ),
    dict(
        id="W23.1",
        section="arbeitswirtschaft",
        topic="Faktorverwertung",
        frage="Der Deckungsbeitrag von Winterweizen beträgt 815 €/ha, der Faktoranspruch 10 AKh/ha. Welche Faktorverwertung ergibt sich daraus für die Arbeit?",
        antwort="82 €/Akh",
        falsch=[
            "815 €/Akh",
            "8,15 €/Akh",
            "45 €/Akh",
        ],
        hinweis="Faktorverwertung = Deckungsbeitrag je Einheit : Faktoranspruch je Einheit = 815 : 10 = 82 €/Akh. Zum Vergleich Milchkuh 3.320 : 50 = 66 €/Akh, Wintergerste 450 : 10 = 45 €/Akh.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 59",
    ),
    dict(
        id="W23.2",
        section="arbeitswirtschaft",
        topic="Arbeitsorganisation",
        frage="Welche Arbeiten zählen zu den termingebundenen Arbeiten?",
        antwort="Melken, Füttern und Ernte – sie sind nicht aufschiebbar und müssen sofort erledigt werden",
        falsch=[
            "Ackern, Düngen und die Büroarbeiten",
            "Hofkehren und Schönheitsreparaturen",
            "Schlepperreinigung und Nachfüllen von Schmierstoffen",
        ],
        hinweis="Unterschieden werden termingebundene (Melken, Füttern, Ernte), laufende (Ackern, Düngen, Büro) und verschiebbare Arbeiten (Hof kehren, Schönheitsreparaturen).",
        quelle="Skripte erste Blockwoche 2025/Arbeitswirtschaft_BW_2025_BiLa_WM.pdf, S. 5",
    ),
    dict(
        id="W23.3",
        section="bw",
        topic="Deckungsbeitrag",
        frage="Wie lautet die allgemeingültige Formel zur Berechnung des Deckungsbeitrags eines Produktionsverfahrens?",
        antwort="Deckungsbeitrag = Marktleistung minus variable Kosten",
        falsch=[
            "Deckungsbeitrag = Marktleistung minus Gesamtkosten",
            "Deckungsbeitrag = variable Kosten minus Marktleistung",
            "Deckungsbeitrag = Marktleistung minus Festkosten",
        ],
        hinweis="Der DB ist eine Teilkostenrechnung: Die Summe der Marktleistungen minus der Summe der variablen Kosten ergibt den Beitrag zur Deckung der Festkosten und zum Gewinn.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 46",
    ),
    dict(
        id="W23.4",
        section="bw",
        topic="Deckungsbeitrag Weizen",
        frage="E-Weizen bringt 65 dt/ha zu 25 €/dt, die variablen Kosten betragen 865 €/ha. Wie hoch ist der Deckungsbeitrag je Hektar?",
        antwort="760 €/ha",
        falsch=[
            "1.625 €/ha",
            "1.115 €/ha",
            "395 €/ha",
        ],
        hinweis="Marktleistung 65 dt x 25 €/dt = 1.625 €/ha, abzüglich 865 €/ha variable Kosten bleiben 760 €/ha. Der Futterweizen mit 90 dt/ha und 1.135 €/ha variablen Kosten kommt dagegen nur auf 395 €/ha.",
        quelle="Skripte erste Blockwoche 2025/Empfehlungen zum visuellen Aufbau - BiLa_BW_Deckungsbeitrag_2024_neu.pdf, Folie 52",
    ),
    dict(
        id="W23.5",
        section="bw",
        topic="Gebäudekosten je kg",
        frage="Der Stallbau eines Betriebes mit 40 Kühen kostet 21.000 € je Kuhplatz, also 840.000 €. Bei 6 % jährlichen Kapitalkosten ergeben sich 50.400 €, bei 9 % 75.600 € Gebäudekosten pro Jahr. Wie hoch ist die Gebäudekostenbelastung je kg Milch bei 7.500 kg Milchleistung je Kuh?",
        antwort="0,17 €/kg bei 6 % und 0,25 €/kg bei 9 % Kapitalkosten",
        falsch=[
            "0,12 €/kg bei 6 % und 0,17 €/kg bei 9 %",
            "0,25 €/kg bei 6 % und 0,17 €/kg bei 9 %",
            "0,06 €/kg bei 6 % und 0,08 €/kg bei 9 %",
        ],
        hinweis="Milchmenge 40 x 7.500 kg = 300.000 kg. 50.400 : 300.000 = 0,17 €/kg, 75.600 : 300.000 = 0,25 €/kg. Bei steigender Milchleistung sinkt die Belastung je kg Milch.",
        quelle="Skripte erste Blockwoche 2025/02_Produktionsfaktor Kapital-Gebäude TN_WM_2025.pdf, Folie 23 und Folie 24",
    ),
    dict(
        id="W20.9",
        section="recht",
        topic="Grundbuch Aufbau",
        frage="Was wird in Abteilung II des Grundbuchs eingetragen?",
        antwort="Nutzungsrechte und Beschränkungen, zum Beispiel Wohnrecht, Nießbrauch und Wegerecht",
        falsch=[
            "Eigentümer und die Art des Erwerbs, zum Beispiel Kauf oder Schenkung",
            "Hypotheken und Grundschulden sowie Rentenschulden",
            "Das Bestandsverzeichnis mit Bezeichnung, Lage und Größe der Grundstücke",
        ],
        hinweis="Abteilung I enthält Eigentümer und Art des Erwerbs, Abteilung II Nutzungsrechte und Beschränkungen, Abteilung III Hypotheken und Grundschulden. Das Bestandsverzeichnis ist Teil des Grundbuchblatts oberhalb der Abteilungen.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 21",
    ),
    dict(
        id="W20.10",
        section="recht",
        topic="Öffentlicher Glaube",
        frage="Was bedeutet der öffentliche Glaube des Grundbuchs?",
        antwort="Alle Eintragungen im Grundbuch sind ohne Nachprüfung als richtig und vollständig zu betrachten",
        falsch=[
            "Der Eintrag ist nur ein Hinweis, das Eigentum geht erst durch mündliche Übergabe über",
            "Eintragungen können nur mit Zustimmung des Katasteramtes geändert werden",
            "Rot unterstrichene Eintragungen sind die aktuell gültigen, ungestrichenen die aufgehobenen",
        ],
        hinweis="Rot unterstrichene Eintragungen sind gelöscht. Das Eigentum geht erst mit der Eintragung der Auflassung in das Grundbuch auf den neuen Eigentümer über, nicht schon mit dem notariellen Kaufvertrag.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 21 und S. 22",
    ),
    dict(
        id="W20.11",
        section="recht",
        topic="Gewerbeabgrenzung",
        frage="Bis zu welchem Anteil darf ein Direktvermarkter Erlöse aus dem Weiterverkauf von zugekauften Produkten erzielen, ohne dass die Landwirtschaft steuerlich als Gewerbe gilt?",
        antwort="Höchstens 30 % vom Umsatz",
        falsch=[
            "Höchstens 10 % vom Umsatz",
            "Höchstens 50 % vom Umsatz",
            "Höchstens ein Drittel vom Umsatz",
        ],
        hinweis="Steuerlich zählt außerdem: Viehbesatz je Hektar darf nicht überschritten werden, Einnahmen aus Dienstleistungen an Landwirte sind auf ein Drittel des Umsatzes und höchstens 51.500 € begrenzt.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 4",
    ),
    dict(
        id="W21.6",
        section="recht",
        topic="Grundsteuerwert",
        frage="Mit welchem Wert je Ar wird der Grundbetrag für landwirtschaftlich genutzte Flächen bei der Grundsteuerwertermittlung angesetzt?",
        antwort="2,52 €/Ar",
        falsch=[
            "6,62 €/Ar",
            "0,041 €/Ar",
            "18,60 €/Ar",
        ],
        hinweis="Grundbetrag = Fläche in Ar x 2,52 €/Ar. Der Ertragsmesszahl werden 0,041 € je Ertragsmesszahl zugesetzt, für die Hofstelle gelten 6,62 €/Ar und der Ertragswert wird mit dem Faktor 18,6 abgeleitet.",
        quelle="Skripte erste Blockwoche 2025/berechnungsbeispiel_des_grundsteuerwerts_eines_betriebs_der_land-_und_forstwirtschaft.pdf, S. 1 und S. 2",
    ),
    dict(
        id="W21.7",
        section="recht",
        topic="Reinertrag",
        frage="Wie hoch ist die Summe der Reinerträge im Berechnungsbeispiel (Flurstück 57: 19.775 €, Flurstück 60: 10.400 €, Hofstelle: 2.482,50 €)?",
        antwort="32.657,50 €",
        falsch=[
            "30.175,00 €",
            "30.657,50 €",
            "28.692,50 €",
        ],
        hinweis="Reinertrag landwirtschaftliche Nutzung = 19.775 + 10.400 = 30.175 €, Reinertrag der Hofstelle 2.482,50 €, Summe der Reinerträge des Betriebs = 32.657,50 €.",
        quelle="Skripte erste Blockwoche 2025/berechnungsbeispiel_des_grundsteuerwerts_eines_betriebs_der_land-_und_forstwirtschaft.pdf, S. 2 und S. 3",
    ),
    dict(
        id="W21.8",
        section="recht",
        topic="Ertragswert",
        frage="Wie wird im land- und forstwirtschaftlichen Bereich der Ertragswert aus der Summe der Reinerträge abgeleitet?",
        antwort="Durch Multiplikation der Summe der Reinerträge mit 18,6",
        falsch=[
            "Durch Multiplikation mit 2,52, dem Grundbetrag je Ar",
            "Durch Multiplikation mit 0,041, dem Ansatz je Ertragsmesszahl",
            "Durch Multiplikation mit 0,7, dem Abschlag für landwirtschaftliche Nutzung",
        ],
        hinweis="Summe der Reinerträge 32.657,50 € x 18,6 = 607.429,50 € Ertragswert. Dieser wird anschließend zur Bildung des Grundsteuerwertes weiterverrechnet.",
        quelle="Skripte erste Blockwoche 2025/berechnungsbeispiel_des_grundsteuerwerts_eines_betriebs_der_land-_und_forstwirtschaft.pdf, S. 1 und S. 3",
    ),
    dict(
        id="W22.16",
        section="recht",
        topic="Hofstelle",
        frage="Wie hoch ist der Flächenwert der Hofstelle im Beispiel, wenn 133 Ar Grundstück vorhanden sind, davon aber 8 Ar Wohnhausgrund, der nicht zur landwirtschaftlichen Nutzung gehört?",
        antwort="2.482,50 € (125 Ar x 6,62 €/Ar mit dreifachem Ansatz)",
        falsch=[
            "827,50 €",
            "3.310,00 €",
            "19.775,00 €",
        ],
        hinweis="133 − 8 = 125 Ar; 125 Ar x 6,62 €/Ar = 827,50 €, mit dreifachem Ansatz der Hofstelle ergibt sich 2.482,50 €. Der Grund und Boden des Wohnhauses zählt zum Grundvermögen und wird hier nicht erfasst.",
        quelle="Skripte erste Blockwoche 2025/berechnungsbeispiel_des_grundsteuerwerts_eines_betriebs_der_land-_und_forstwirtschaft.pdf, S. 2",
    ),
    dict(
        id="W22.17",
        section="recht",
        topic="Liegenschaftskataster",
        frage="Wer führt das Liegenschaftskataster und welche Buchungseinheit hat es?",
        antwort="Das zuständige Vermessungsamt; Buchungseinheit ist das Flurstück, die Amtsbezirke sind deckungsgleich mit den Landkreisen",
        falsch=[
            "Das Grundbuchamt am Amtsgericht; Buchungseinheit ist das Grundstück mit Gebäude",
            "Das Finanzamt; Buchungseinheit ist das Steuerobjekt",
            "Das Landratsamt; Buchungseinheit ist die Gemarkung",
        ],
        hinweis="Im Kataster werden Gestalt, Größe, örtliche Lage, Nutzung und Eigentumsverhältnisse aller Grundstücke und Gebäude beschrieben. Das Kataster wird vom Amt für Digitalisierung, Breitband und Vermessung geführt.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 17",
    ),
    dict(
        id="W22.18",
        section="recht",
        topic="Bodenschätzung",
        frage="Welche Angaben gehören zum Ackerschätzungsrahmen und welche Größe ergibt sich daraus?",
        antwort="Bodenart (S, Sl, lS, SL, sL, L, LT, T, Mo), Zustandsstufe arabisch 1 bis 7 und Entstehung (D, Lö, AL, V, Vg); daraus die Bodenzahl und mit Zu- und Abschlägen die Ackerzahl",
        falsch=[
            "Bodenart, Zustandsstufe römisch I bis III und Klima; daraus Grünlandgrundzahl und Grünlandzahl",
            "Bodenart, Wasserverhältnisse 1 bis 5 und Entstehung; daraus unmittelbar der Ertragswert",
            "Zustandsstufe arabisch 1 bis 7 und Klima von a bis d; daraus die Bodenzahl des Ackerlandes",
        ],
        hinweis="Der Ackerschätzungsrahmen wird mit arabischen Zustandsstufen geführt, der Grünlandschätzungsrahmen mit römischen (I, II, III) sowie Klima und Wasserverhältnissen. Die zweite Zahl der Klassenbeschreibung zeigt Acker- oder Grünlandzustand.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 13 und S. 14",
    ),
    dict(
        id="W23.7",
        section="recht",
        topic="Außenbereich",
        frage="Welche Voraussetzung muss für die Privilegierung eines landwirtschaftlichen Betriebes im Außenbereich nach § 35 BauGB vorliegen?",
        antwort="Das landwirtschaftliche Einkommen muss ein wesentlicher Teil des Gesamteinkommens sein",
        falsch=[
            "Der Betrieb muss mehr als 5 ha LF bewirtschaften",
            "Der Betrieb muss mindestens 3.000 m² landwirtschaftlich genutzte Fläche haben",
            "Der Betrieb muss eine Tierhaltung mit mindestens 2 Vieheinheiten je Hektar betreiben",
        ],
        hinweis="Nach § 35 BauGB wird ein Vorhaben im Außenbereich privilegiert, wenn es einer landwirtschaftlichen Nutzung zu Erwerbszwecken dient, das landwirtschaftliche Einkommen wesentlicher Teil des Gesamteinkommens ist und die Betriebsführung nachhaltig ist.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 4",
    ),
    dict(
        id="W23.8",
        section="recht",
        topic="Förderschwellen",
        frage="Ab welcher Mindestbetriebsgröße werden KULAP und Ausgleichszulage im Einzelbetrieb gewährt?",
        antwort="Ab 3 ha LF",
        falsch=[
            "Ab 1 ha LF",
            "Ab 8 ha LF",
            "Ab 20 ha LF",
        ],
        hinweis="Ab 3 ha LF KULAP und Ausgleichszulage, ab 1 ha LF der Mehrfachantrag, ab 0,25 ha landwirtschaftlicher Bodennutzung die Möglichkeit des MFA, ab 0,3 ha LF das Vertragsnaturschutzprogramm. Für VNP und die Betriebsprämie (0,1 ha und mindestens 100 € je Betrieb) gilt keine Mindestgröße der LF.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 4",
    ),
    dict(
        id="W23.9",
        section="recht",
        topic="Katasterinhalt",
        frage="Welche Aufgabe erfüllt das Liegenschaftskataster unter anderem bei der Bodenbewertung?",
        antwort="Es dient zur Ermittlung des Ertragswertes aus Ertragsmesszahlen und Bodenfläche sowie zur Berechnung des Einheitswertes",
        falsch=[
            "Es ermittelt laufend den Marktwert des Bodens aus den Bodenrichtwerten",
            "Es stellt die Steuerschuld des Eigentümers gegenüber dem Finanzamt fest",
            "Es verwaltet die Förderanträge der Betriebe und prüft die Fördervoraussetzungen",
        ],
        hinweis="Weitere Bedeutungen sind die Berechnung von Erträgen, die Herleitung von Entschädigungen, Voranschläge für Düngung und Pflanzenschutz sowie die Kalkulation von Arbeitszeitbedarf und Maschinenkosten.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 18",
    ),
    dict(
        id="W20.12",
        section="sozialkunde",
        topic="Alterskasse",
        frage="Ab welcher Mindestbetriebsgröße besteht die Pflichtmitgliedschaft in der Landwirtschaftlichen Alterskasse (LAK)?",
        antwort="Ab 8 ha landwirtschaftlich genutzter Fläche",
        falsch=[
            "Ab 1 ha LF",
            "Ab 3 ha LF",
            "Ab 20 ha LF",
        ],
        hinweis="Die Mindestbetriebsgröße der LAK liegt bei 8 ha LF. Für die Landwirtschaftliche Krankenkasse ist der hauptberufliche Landwirt mit weniger als 18 Stunden Wochenarbeit außerhalb der Landwirtschaft maßgeblich.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 4",
    ),
    dict(
        id="W20.13",
        section="sozialkunde",
        topic="Krankenkasse",
        frage="Wer ist Mitglied in der Landwirtschaftlichen Krankenkasse (LKK)?",
        antwort="Der hauptberufliche Landwirt, der weniger als 18 Stunden pro Woche außerhalb der Landwirtschaft tätig ist",
        falsch=[
            "Jeder Landwirt ohne Rücksicht auf die Wochenarbeitszeit außerhalb der Landwirtschaft",
            "Alle Betriebe, die mindestens 2.500 m² landwirtschaftliche Fläche bewirtschaften",
            "Alle Landwirte mit mindestens 40 Milchkühen, unabhängig ihrer Tätigkeit",
        ],
        hinweis="Der hauptberufliche Einsatz in der Landwirtschaft entscheidet über die Mitgliedschaft. Wer daneben außerlandwirtschaftlich mehr als 18 Stunden pro Woche arbeitet, ist nicht mehr in der LKK versichert.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 4",
    ),
    dict(
        id="W20.14",
        section="sozialkunde",
        topic="Berufsgenossenschaft",
        frage="Unter welcher Voraussetzung ist eine Befreiung von der Landwirtschaftlichen Berufsgenossenschaft (LBG) möglich?",
        antwort="Wenn weniger als 2.500 m² landwirtschaftliche Fläche bewirtschaftet werden",
        falsch=[
            "Wenn der Betrieb mehr als 8 ha LF bewirtschaftet",
            "Wenn weniger als 18 Stunden pro Woche außerlandwirtschaftlich gearbeitet wird",
            "Wenn der Viehbesatz unter 2 Vieheinheiten je Hektar liegt",
        ],
        hinweis="Die landwirtschaftliche Berufsgenossenschaft ist zuständig für die Unfallversicherung der landwirtschaftlichen Unternehmen; eine Befreiung ist bei weniger als 2.500 m² LF möglich.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 4",
    ),
    dict(
        id="W20.15",
        section="sozialkunde",
        topic="Marktkreislauf",
        frage="Welche Phasen werden beim Ablauf des Marktkreislaufs unterschieden?",
        antwort="Boom, Stagnation, Rezession und Depression",
        falsch=[
            "Inflation, Rezession, Stagnation und Erholung",
            "Gründung, Wachstum, Reife und Zerfall",
            "Boom, Rezession, Depression und Inflation",
        ],
        hinweis="Der Marktkreislauf beschreibt den konjunkturellen Verlauf der Wirtschaft: Boom, Stagnation, Rezession und Depression. Für die Prüfung ist außerdem das aktuelle Geschehen zu Wahlen, Kriegen und Protesten sowie die Direktvermarktung und ihre Marketingstrategien wichtig.",
        quelle="Skripte erste Blockwoche 2025/Grundlagen der BL_Skript_Grundbuch_Liegenschaftskataster.pdf, S. 11",
    ),
    dict(
        id="W23.10",
        section="sozialkunde",
        topic="Biotopschutz",
        frage="Was ist über gesetzlich geschützte Biotope richtig?",
        antwort="Sie sind nach § 30 BNatSchG und Art. 23 BayNatSchG kraft Gesetzes geschützt; eine Kartierung oder Bekanntmachung ist nicht nötig",
        falsch=[
            "Sie müssen vom Landwirt vor jeder Nutzung beim Naturschutzamt angezeigt werden",
            "Sie sind nur geschützt, wenn sie im Flächen- oder Biotopkataster des Naturschutzamtes eingetragen sind",
            "Sie dürfen bewirtschaftet werden, wenn die Gemeinde eine Genehmigung erteilt hat",
        ],
        hinweis="Unzulässig sind Maßnahmen, die zu einer Zerstörung oder sonstigen erheblichen Beeinträchtigung führen. Geschützt sind unter anderem Moore und Moorwälder, Bruch-, Sumpf- und Auwälder sowie Quellbereiche.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldrecht_NatSch_Jagd_Förderung.pdf, Folie 27",
    ),
    dict(
        id="W23.11",
        section="sozialkunde",
        topic="Natura 2000",
        frage="Woraus besteht Natura 2000 und welcher Kernbegriff prägt diesen internationalen Biotopverbund?",
        antwort="Aus FFH-Gebieten und Vogelschutzgebieten; der Kernbegriff ist das Verschlechterungsverbot",
        falsch=[
            "Aus FFH-Gebieten allein; das Verschlechterungsverbot gilt erst nach Erklärung zum Nationalpark",
            "Aus Nationalparks, Biosphärenreservaten und Landschaftsschutzgebieten mit Betretungsverbot",
            "Aus FFH- und Vogelschutzgebieten mit dem Grundsatz des ganzheitlichen Betretensverbots",
        ],
        hinweis="Natura 2000 ist ein europaweiter Biotopverbund mit dem Ziel, Lebensräume und Arten in gutem Zustand zu erhalten. In Bayern liegen 745 Gebiete mit rund 801.300 ha, das sind 11 % der Landesfläche und 18 % der Waldfläche.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldrecht_NatSch_Jagd_Förderung.pdf, Folie 30 und Folie 31",
    ),
    dict(
        id="W23.12",
        section="sozialkunde",
        topic="Artenschutz",
        frage="Was gilt für streng geschützte Arten im landwirtschaftlichen Betrieb?",
        antwort="Zusätzlich ist die erhebliche Störung verboten; die ordnungsgemäße land- und forstwirtschaftliche Nutzung bleibt zulässig, solange sich der Erhaltungszustand der lokalen Population nicht verschlechtert",
        falsch=[
            "Streng geschützte Arten dürfen auch bei landwirtschaftlicher Nutzung nicht gestört werden, auch nicht mittelbar",
            "Der Schutz gilt ausschließlich innerhalb von Naturschutzgebieten",
            "Für streng geschützte Arten gelten dieselben Regelungen wie für besonders geschützte Arten",
        ],
        hinweis="Der allgemeine Artenschutz nach §§ 39 bis 43 BNatSchG gilt für alle wild lebenden Tier- und Pflanzenarten; bei streng geschützten Arten ist zusätzlich die erhebliche Störung untersagt, etwa das Fällen von Biotopbäumen.",
        quelle="Skripte erste Blockwoche 2025/2025_BiLa Waldrecht_NatSch_Jagd_Förderung.pdf, Folie 28 und Folie 29",
    ),
]
