"""Fragen der BiLa-Abschlussprüfung 2021, Prüfungsfach Pflanzenproduktion.

Antworten belegt aus dem Unterrichtsmaterial in bila_25-27/.
Nicht belegbare Aufgaben (Abbildungen, fehlende Zahlenwerte im PDF) sind
bewusst nicht enthalten.
"""

SECTIONS = {
    "1": "Grundlagen – Pflanzen säen und vermehren (20 P)",
    "2": "Grundlagen – Pflanzen ernähren (20 P)",
    "3": "Grundlagen – Pflanzen pflegen und ernten (20 P)",
    "4": "Schwerpunkt Getreidebau (20 P)",
    "5": "Schwerpunkt Ackerfutterbau (20 P)",
    "6": "Schwerpunkt Grünland (20 P)",
    "7": "Schwerpunkt Waldbau (20 P)",
}

QUESTIONS = [
    # ---------------- 1. Pflanzen säen und vermehren ----------------
    dict(
        id="1.1", section="1", topic="Saatgut",
        frage="Sie verwenden Z-Saatgut und Nachbausaatgut. Welches Merkmal ist für Z-Saatgut (zertifiziertes Saatgut) zwingend gefordert?",
        antwort="Frei von samenbürtigen Krankheiten (z. B. Stein- und Flugbrand)",
        falsch=[
            "Es ist chemisch gebeizt und braucht deshalb keine weitere Behandlung",
            "Es wird mit 100 % Keimfähigkeit garantiert",
            "Es muss mindestens 10 Prozent Keimfähigkeit mehr haben als Nachbausaatgut",
        ],
        hinweis="Stein- und Flugbrand sind samenbürtig – beim Getreidebau wird die Beizung ausdrücklich als Gegenmaßnahme genannt.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 62/71",
    ),
    dict(
        id="1.2", section="1", topic="Sortenwahl",
        frage="Sie stehen vor der Sortenwahl für Wintergerste. Wonach richten Sie sich bei der Auswahl einer Sorte?",
        antwort="Nach Ertragspotenzial, Winterhärte, Reifezeit und Krankheitsresistenz",
        falsch=[
            "Nach dem Namen des Saatgutproduzenten",
            "Nach der Farbe des Saatgutbeutels",
            "Nach der Reihenfolge der Sortenliste",
        ],
        hinweis="Die Skriptseite „Kriterien zur Sortenwahl“ nennt u. a. Verwertung, Ertrag, Boden-/Klimaverhältnisse, Saatzeit, Krankheitsresistenz und Halmlänge.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 74/75",
    ),
    dict(
        id="1.3", section="1", topic="Ertragsermittlung",
        frage="Wintergerstensorte Sandra liegt in Stufe 2 bei 97 % Relativertrag. Wie hoch ist die mehrjährige durchschnittliche Ertragsleistung bei Ø dt/ha = 100 % = 89,6?",
        antwort="rund 87 dt/ha (97 % von 89,6 dt/ha)",
        falsch=["89,6 dt/ha", "79,4 dt/ha", "96,0 dt/ha"],
        hinweis="Rechnung: 89,6 × 0,97 = 86,9 dt/ha.",
        quelle="Prüfungsaufgabe 1.3, Auszug Integrierter Pflanzenbau",
    ),
    dict(
        id="1.4", section="1", topic="Beizung",
        frage="Nennen Sie einen Vorteil der chemischen Saatgutbeizung im Getreide.",
        antwort="Schutz gegen samenbürtige Krankheiten wie Stein- und Flugbrand",
        falsch=[
            "Steigerung der Keimfähigkeit auf über 100 %",
            "Umwandlung von Nachbausaatgut in Z-Saatgut",
            "Ersatz der Saatgutreinigung",
        ],
        hinweis="Weitere Vorteile: gleichmäßiger und sicherer Wirkungserfolg unabhängig von Bodenverhältnissen, kein zusätzlicher Arbeitsgang.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 62/71",
    ),
    dict(
        id="1.5", section="1", topic="Beizung",
        frage="Welches Verfahren ist eine Alternative zur chemischen Saatgutbeizung im Getreide?",
        antwort="Thermobehandlung mit Heißwasser",
        falsch=[
            "Behandlung mit Kalkstaub",
            "Lagerung in feuchter Keimkammer",
            "Bestrahlung mit UV-Licht",
        ],
        hinweis="Alternativ kommen thermische Verfahren (Heißwasser, Heißluft) oder mechanische Oberflächenbehandlung in Frage.",
        quelle="Prüfungsaufgabe 1.5 (Antwort: thermisches Verfahren)",
    ),
    dict(
        id="1.6.1", section="1", topic="Aussaatmenge",
        frage="Wie lautet die allgemeine Formel für die Aussaatmenge in kg/ha?",
        antwort="kg/ha = Körner je m² × Tausendkorngewicht (g) ÷ Keimfähigkeit (in %)",
        falsch=[
            "kg/ha = Körner je m² × Tausendkorngewicht (g) × Keimfähigkeit (in %)",
            "kg/ha = Körner je m² ÷ Tausendkorngewicht (g) × Keimfähigkeit (in %)",
            "kg/ha = Körner je m² × Tausendkorngewicht (g) ÷ Keimfähigkeit × 10",
        ],
        hinweis="Die Keimfähigkeit wird als Prozentwert, nicht als Dezimalzahl eingesetzt.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 51",
    ),
    dict(
        id="1.6.2", section="1", topic="Aussaatmenge",
        frage="Empfehlung 310 keimfähige Körner/m², Keimfähigkeit 93 %, Tausendkorngewicht 60 g. Welche Aussaatmenge ergibt sich?",
        antwort="rund 200 kg/ha (310 × 60 ÷ 93)",
        falsch=["rund 172 kg/ha", "rund 232 kg/ha", "rund 255 kg/ha"],
        hinweis="310 × 60 = 18.600; 18.600 ÷ 93 = 200 kg/ha.",
        quelle="Prüfungsaufgabe 1.6.1",
    ),
    dict(
        id="1.6.3", section="1", topic="Saatgutkosten",
        frage="Z-Saatgut kostet 65,00 €/dt, Aussaatmenge 190 kg/ha. Welche Saatgutkosten entstehen für 1,5 ha Z-Saatgutfläche?",
        antwort="rund 185,25 € (285 kg = 2,85 dt × 65,00 €/dt)",
        falsch=["rund 264,00 €", "rund 370,50 €", "rund 123,50 €"],
        hinweis="1,5 ha × 190 kg/ha = 285 kg = 2,85 dt; 2,85 × 65,00 € = 185,25 €.",
        quelle="Prüfungsaufgabe 1.6.3",
    ),
    dict(
        id="1.7", section="1", topic="Nachbaugebühr",
        frage="Warum sind Nachbaugebühren gerechtfertigt?",
        antwort="Sie vergüten die Nutzung der geschützten Sorte gegenüber dem Saatgutzüchter",
        falsch=[
            "Sie ersetzen die Kosten für Reinigung und Beizung",
            "Sie sind eine Abgabe an die Finanzverwaltung",
            "Sie bezuschussen den Kauf von Z-Saatgut",
        ],
        hinweis="Die Gebühr ist der wirtschaftliche Ausgleich für die Weiterzucht und den Sortenschutz beim Saatgutzüchter.",
        quelle="Prüfungsaufgabe 1.7; BiLa Grundlagen Waldwirtschaft (FoVG)",
    ),
    # ---------------- 2. Pflanzen ernähren ----------------
    dict(
        id="2.1", section="2", topic="N-Bedarf Grünland",
        frage="Von welchem Faktor hängt der berechnete Stickstoffbedarf Ihrer Grünlandflächen ab?",
        antwort="Vom Ertragsniveau, also von Anzahl und Höhe der Schnitte",
        falsch=[
            "Vom Trockensubstanzgehalt der Silage",
            "Vom Kaufpreis des Stickstoffdüngers",
            "Vom Sortennamen der Gräser",
        ],
        hinweis="Je höher der Ertrag und je mehr Schnitte, desto höher der N-Bedarf und damit der berechnete Nährstoffbedarf.",
        quelle="03_Grundlagen Düngung BiLa Reindl 2025",
    ),
    dict(
        id="2.2a", section="2", topic="Düngeverordnung",
        frage="Wie viel kg Gesamtstickstoff dürfen Sie laut Düngeverordnung maximal je ha und Jahr aus organischen Düngemitteln ausbringen?",
        antwort="170 kg N je ha und Jahr (im Durchschnitt der Betriebsflächen)",
        falsch=["120 kg N je ha und Jahr", "230 kg N je ha und Jahr", "290 kg N je ha und Jahr"],
        hinweis="Die 290 kg N/ha sind Ihr aus der Fläche berechneter N-Bedarf, nicht die Obergrenze.",
        quelle="04_Gesetzliche Grundlagen Pflanzenbau BiLa Reindl 2025, Folie 22",
    ),
    dict(
        id="2.2b", section="2", topic="Güllemenge",
        frage="Ihre Rindergülle enthält 3,8 kg N gesamt je m³. Welche Menge entspricht der Obergrenze von 170 kg N/ha?",
        antwort="rund 45 m³ Gülle je ha (170 ÷ 3,8)",
        falsch=["rund 55 m³ je ha", "rund 32 m³ je ha", "rund 78 m³ je ha"],
        hinweis="170 kg N ÷ 3,8 kg N/m³ = 44,7 m³/ha.",
        quelle="Prüfungsaufgabe 2.2",
    ),
    dict(
        id="2.3", section="2", topic="Gülleausbringung",
        frage="Sie bringen 44,7 m³ Gülle je ha aus, die Pumpe fördert 3 m³ pro Minute, die Arbeitsbreite beträgt 18 m. Mit welcher Geschwindigkeit müssen Sie fahren?",
        antwort="rund 2,2 km/h",
        falsch=["rund 8 km/h", "rund 12 km/h", "rund 0,6 km/h"],
        hinweis="Fläche je Minute = 3 m³ ÷ 44,7 m³/ha = 671 m²; 671 m² ÷ 18 m = 37 m/min = 2,2 km/h.",
        quelle="Prüfungsaufgabe 2.3",
    ),
    dict(
        id="2.4.1a", section="2", topic="Stickstoffformen",
        frage="Welche Stickstoffformen enthält die Gülle?",
        antwort="Ammonium-Stickstoff (NH4+) und organisch gebundenen Stickstoff",
        falsch=[
            "Nur Nitratstickstoff (NO3-)",
            "Ammoniak-Stickstoff (NH3) und Nitratstickstoff",
            "Ausschließlich Amid-Stickstoff",
        ],
        hinweis="In der Gülle ist etwa zur Hälfte Ammonium-N, zur Hälfte organisch gebundener N enthalten.",
        quelle="03_Grundlagen Düngung BiLa Reindl 2025, Folie 30",
    ),
    dict(
        id="2.4.1b", section="2", topic="Mineralisation",
        frage="Wovon hängt es ab, wie schnell der organisch gebundene Stickstoff im Boden mineralisiert wird?",
        antwort="Von Bodentemperatur, Luft- und Wasserhaushalt, pH-Wert und C:N-Verhältnis",
        falsch=[
            "Vom Kaliumgehalt des Bodens",
            "Vom Kornanteil der Fruchtfolge",
            "Vom Zeitpunkt der Gülleuntersuchung",
        ],
        hinweis="Optimal ist eine Bodentemperatur von 15–20 °C; hohe Temperaturen fördern dagegen die Ammoniakverluste.",
        quelle="03_Grundlagen Düngung BiLa Reindl 2025, Folie 33",
    ),
    dict(
        id="2.4.2a", section="2", topic="Gewässerabstand",
        frage="Welchen Mindestabstand zu Oberflächengewässern müssen Sie beim Ausbringen flüssiger organischer Dünger auf Ackerland bei mindestens 15 % Hangneigung einhalten?",
        antwort="Mindestens 10 m (bei zusätzlichem Auflagenvorbehalt bis 30 m)",
        falsch=["Mindestens 1 m", "Mindestens 5 m", "Mindestens 20 m"],
        hinweis="Bei ≥ 15 % Hangneigung gilt ein Abstand von 10 m bzw. 30 m mit zusätzlichen Auflagen; unter 5 % sind es 1 m bzw. 4 m.",
        quelle="04_Gesetzliche Grundlagen Pflanzenbau BiLa Reindl 2025, Folie 57",
    ),
    dict(
        id="2.4.2b", section="2", topic="Einarbeitung",
        frage="Seit wann gilt die Einarbeitungspflicht innerhalb einer Stunde für organische Düngemittel mit wesentlichem Anteil an verfügbarem Stickstoff auf unbestelltes Ackerland?",
        antwort="Seit 1. Februar 2025",
        falsch=["Seit 1. Januar 2015", "Seit 1. Januar 2020", "Seit 1. Februar 2020"],
        hinweis="Harnstoff darf seit 2020 nur mit Ureasehemmer oder innerhalb von 4 Stunden eingearbeitet werden.",
        quelle="04_Gesetzliche Grundlagen Pflanzenbau BiLa Reindl 2025, Folie 58",
    ),
    dict(
        id="2.5.1", section="2", topic="Kalkwert",
        frage="SSA hat eine Kalkwirkung von – 63 kg CaO je 100 kg Dünger. Was bedeutet das?",
        antwort="Der Dünger bindet Kalk – 63 kg CaO je 100 kg Dünger müssen durch Kalkgabe ausgeglichen werden",
        falsch=[
            "Der Dünger enthält 63 kg CaO und wirkt daher kalkend",
            "Der pH-Wert des Bodens wird um 63 Einheiten angehoben",
            "Pro 100 kg Dünger dürfen nur 63 kg Kalk ausgebracht werden",
        ],
        hinweis="Negativer Kalkwert = versauernde, kalkzehrende Wirkung des Düngers.",
        quelle="Prüfungsaufgabe 2.5.1; 03_Grundlagen Düngung Folie 19",
    ),
    dict(
        id="2.5.2", section="2", topic="Kalkwirkung",
        frage="Welche Wirkung hat Kalk auf den Boden?",
        antwort="Anhebung des pH-Werts und Verbesserung der Bodenstruktur (Krümelbildung)",
        falsch=[
            "Senkung des pH-Werts und Verdichtung der Krume",
            "Erhöhung der Auswaschungsgefahr von Nährstoffen",
            "Hemmung der biologischen Aktivität im Boden",
        ],
        hinweis="Weitere Kalkeffekte: Entsäuerung, Förderung der Bodenlebewesen, bessere Wasserspeicherung und Mobilisierung von Nährstoffen.",
        quelle="03_Grundlagen Düngung BiLa Reindl 2025, Folie 17/18",
    ),
    dict(
        id="2.5.3", section="2", topic="Schwefel",
        frage="SSA enthält zusätzlich Schwefel. Welche Rolle spielt Schwefel in der Pflanze?",
        antwort="Er ist Baustein der Aminosäuren und damit des Eiweißes, der Enzyme und Vitamine",
        falsch=[
            "Er ist Hauptbestandteil des Chlorophylls",
            "Er wird von der Pflanze als Nitratform aufgenommen",
            "Er erhöht ausschließlich die Winterhärte der Kultur",
        ],
        hinweis="Schwefel wird nur als Sulfat aufgenommen und ist im Boden stark auswaschungsgefährdet – daher bedarfsgerecht düngen.",
        quelle="03_Grundlagen Düngung BiLa Reindl 2025, Folie 64/65",
    ),
    # ---------------- 3. Pflanzen pflegen und ernten ----------------
    dict(
        id="3.1", section="3", topic="Beikrautregulierung",
        frage="Welche Fruchtfolgegrundregel wirkt im Integrierten Pflanzenbau am stärksten vorbeugend gegen Verunkrautung?",
        antwort="Wechsel zwischen Halm- und Blattfrüchten (etwa 50 : 50)",
        falsch=[
            "Möglichst viele Winterungen in der Fruchtfolge",
            "Anbau von Kulturen mit langsamer Jugendentwicklung",
            "Möglichst viele Zwischenfrüchte mit hohem Kleeanteil",
        ],
        hinweis="Weitere vorbeugende Maßnahmen: konkurrierende Kultur und Sorte wählen, Untersaaten und Zwischenfrüchte nutzen, falsches Saatbett, keine Verschleppung von Unkrautsamen.",
        quelle="Grundlagen des Ökolandbaus Pflanze BiLa Bayern 2025, Folie 39/43",
    ),
    dict(
        id="3.2", section="3", topic="Striegeln",
        frage="Worauf müssen Sie beim Einsatz des Striegels im Getreidebestand achten?",
        antwort="Auf ein frühes Unkrautstadium (Keimblatt/kleine Rosette) und flach eingestellte Zinken",
        falsch=[
            "Auf ein spätes Rosettestadium und tief eingestellte Zinken",
            "Auf möglichst feuchten Boden, damit der Striegel gut greift",
            "Auf den Einsatz erst nach der Ernte auf der Stoppel",
        ],
        hinweis="Wirkungsgrad Striegel: Keimblatt 80–90 %, kleine Rosette 70–75 %, große Rosette nur 50–55 %. Blindstriegeln 3–7 Tage nach der Saat.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 69/70; Ökolandbau Folie 49",
    ),
    dict(
        id="3.3", section="3", topic="Gründüngung",
        frage="Welches Ziel verfolgt die Gründüngung mit Zwischenfrüchten neben der Nährstoffkonservierung?",
        antwort="Schutz vor Bodenabschwemmung und Erosionsschäden",
        falsch=[
            "Verlängerung der Lagerfähigkeit des Korns",
            "Erhöhung des pH-Werts im Boden",
            "Beschleunigung der Ernte der folgenden Hauptfrucht",
        ],
        hinweis="Weitere Ziele: Unterdrückung von Beikraut, Humusaufbau und Durchwurzelung, N-Anreicherung durch Leguminosen.",
        quelle="BiLa 25-27 Ackerfutterbau und Konservierung, Folie 107",
    ),
    dict(
        id="3.4", section="3", topic="Herbizidauswahl",
        frage="Nach welchem Grundsatz wählen Sie Wirkstoffe für eine Herbizidfolge aus?",
        antwort="Nachfolge-Anwendungen sollen nicht denselben Wirkmechanismus nutzen (Resistenzmanagement)",
        falsch=[
            "Immer dasselbe Mittel einsetzen, damit man die Anwendung kennt",
            "Grundsätzlich die höchste Aufwandmenge verwenden",
            "Anwendung erst nach der Ernte, wenn das Getreide standfest ist",
        ],
        hinweis="Weitere Auswahlkriterien: Wirkungsprofil gegen die vorhandene Unkrautflora, Standort- und Kulturverträglichkeit, Gewässerabstände, Wirkdauer und Nachfolgekultur.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 58/68",
    ),
    dict(
        id="3.5", section="3", topic="Pilzkrankheiten",
        frage="Welche Kulturmaßnahmen begünstigen Pilzbefall im Getreide?",
        antwort="Übermäßige Stickstoffdüngung und zu dichte Bestände mit langer Blattbenetzungszeit",
        falsch=[
            "Niedrige Stickstoffgabe und weiter Reihenabstand",
            "Trockene Witterung und gut durchlüftete Böden",
            "Frühzeitige Saatgutbeizung und Fruchtfolgewechsel",
        ],
        hinweis="Weitere Ursachen: lange Vegetationszeit durch frühe Aussaat, Stoppelreste ohne Bodenbearbeitung, feuchte Witterung und anfällige Sorten.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 48/106",
    ),
    # ---------------- Schwerpunkt Getreidebau ----------------
    dict(
        id="SP1.1", section="4", topic="Aussaatzeit",
        frage="Welche Folgen kann eine zu frühe Aussaat der Wintergerste haben?",
        antwort="Höherer Krankheitsdruck und höhere Auswinterungsgefahr",
        falsch=[
            "Weniger Unkrautdruck und höhere Ertragssicherheit",
            "Höhere Winterhärte und geringere Lagergefahr",
            "Bessere Nährstoffaufnahme und geringerer Pflegbedarf",
        ],
        hinweis="Frühe Saaten haben eine längere Infektionszeit für Halmbruch, Schwarzbeinigkeit, Mehltau und Rost sowie höheres Risiko für Blattläuse (Gelbverzwergungsvirus).",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 48",
    ),
    dict(
        id="SP1.2a", section="4", topic="pH-Wert",
        frage="In welchem pH-Bereich sollte der Boden für Wintergerste liegen?",
        antwort="Im neutralen Bereich, etwa pH 6,0–7,0",
        falsch=["Im stark sauren Bereich, pH 4,5–5,0", "Im stark basischen Bereich, pH 8,0–8,5", "Im schwach sauren Bereich, pH 4,0–5,0"],
        hinweis="Bei pH 6,0–7,0 sind Haupt- und Spurennährstoffe voll verfügbar.",
        quelle="01_Grundlagen Getreidebau Folie 38; 03_Grundlagen Düngung Folie 16",
    ),
    dict(
        id="SP1.2b", section="4", topic="pH-Wert",
        frage="Was passiert im Boden bei einem pH-Wert unter 5,0?",
        antwort="Phosphor wird festgelegt und pflanzenschädliches Aluminium wird freigesetzt",
        falsch=[
            "Alle Nährstoffe werden besser verfügbar",
            "Es entsteht vor allem ein zu hoher Salzgehalt",
            "Die Kalkwirkung von Düngemitteln wird verstärkt",
        ],
        hinweis="Bei pH über 7,5 sind dagegen vor allem Phosphat und einige Spurenelemente festgelegt.",
        quelle="03_Grundlagen Düngung BiLa Reindl 2025, Folie 16",
    ),
    dict(
        id="SP1.3", section="4", topic="Braugerste",
        frage="Was sind typische Qualitätskriterien für Braugerste?",
        antwort="Hoher Vollgerstenanteil (über 90 %) und niedriger Eiweißgehalt (unter 11,5 %)",
        falsch=[
            "Hoher Eiweißgehalt über 13 % und hoher Fremdbesatz",
            "Feuchtigkeit über 16 % und niedriger Vollgerstenanteil",
            "Ausschließlich Tausendkorngewicht und Feuchtigkeit",
        ],
        hinweis="Weitere Anforderungen: Feuchte unter 15 %, geringe Schälfrüchte- und Malzextraktionsverluste, gesundes Saatgut mit hoher Keimfähigkeit.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 41",
    ),
    dict(
        id="SP1.4", section="4", topic="Braugerste",
        frage="Worauf ist bei der Stickstoffdüngung von Braugerste zu achten?",
        antwort="Die N-Gabe niedrig und bedarfsgerecht halten, damit der Eiweißgehalt nicht zu hoch wird",
        falsch=[
            "Die N-Gabe über 200 kg N/ha hinaus steigern, um den Ertrag zu maximieren",
            "Den gesamten Stickstoff im Herbst ausbringen",
            "Auf die Düngung ganz verzichten und nur Wirtschaftsdünger verwenden",
        ],
        hinweis="Ein zu hoher Eiweißgehalt verschlechtert die Malzqualität; beim Brotweizen ist ein hoher Proteingehalt dagegen erwünscht.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 84/89",
    ),
    dict(
        id="SP1.5", section="4", topic="Trocknung",
        frage="Sie dreschen 120 t Winterweizen mit 17,7 % Feuchtigkeit und trocknen auf 14,5 % Restfeuchte. Wie viele dt werden eingelagert?",
        antwort="rund 1.155 dt",
        falsch=["1.200 dt", "987 dt", "1.340 dt"],
        hinweis="Trockensubstanz = 120 × 0,823 = 98,76 t; 98,76 ÷ 0,855 = 115,5 t = 1.155 dt.",
        quelle="Prüfungsaufgabe 1.5; 01_Grundlagen Getreidebau Folie 88",
    ),
    dict(
        id="SP1.6", section="4", topic="Kornkäfer",
        frage="Welche Schäden kann der Kornkäfer verursachen?",
        antwort="Fraß an Keim- und Triebteilen sowie am Korn – Ausfall des Aufwuchses und Qualitätsverlust",
        falsch=[
            "Nur Fraß an den Blättern im Freiland",
            "Nur Feuchtigkeitsverlust ohne Qualitätswirkung",
            "Ausschließlich Schäden am Stroh",
        ],
        hinweis="Der Kornkäfer schadet als Vorratsschädling zusätzlich durch erhöhte Lagerfeuchte und Begünstigung von Schimmelpilzen.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 88/92",
    ),
    dict(
        id="SP1.7", section="4", topic="Kornkäfer",
        frage="Welche Sofortmaßnahmen können Sie bei Kornkäferbefall im Lager ergreifen?",
        antwort="Lagergetreide kühlen und belüften und die befallene Partie umlagern",
        falsch=[
            "Das Getreide feucht halten und die Lüftung stoppen",
            "Abwarten bis zur nächsten Ernte, eine Kühlung ist nicht nötig",
            "Den Lagerraum mit feuchter Erde auffüllen",
        ],
        hinweis="Bei bereits starkem Befall bleibt oft nur die chemische Behandlung oder ein Abtransport der Partie.",
        quelle="Prüfungsaufgabe 1.7",
    ),
    dict(
        id="SP1.8", section="4", topic="Lagerung",
        frage="Wie können Sie einen Kornkäferbefall im Lager künftig vermeiden?",
        antwort="Trockenes, kühles und dichtes Lager mit regelmäßiger Befallskontrolle",
        falsch=[
            "Warmes, feuchtes Lager mit dauerhaft geöffneter Lüftung",
            "Lagerung unmittelbar neben dem Stall",
            "Keine Kontrolle, weil Lagerkorn ohnehin schnell verdirbt",
        ],
        hinweis="Kornfeuchte unter 14 % lagern, Getreide vor der Einlagerung auf Vorratskäfer kontrollieren und Kühlung und Belüftung nutzen.",
        quelle="01_Grundlagen Getreidebau BiLa 2026, Folie 88/94",
    ),
    # ---------------- Schwerpunkt Ackerfutterbau ----------------
    dict(
        id="SP5.1", section="5", topic="Futterpflanzen",
        frage="Welche der genannten Futterpflanzen gehören zu den Leguminosen (Schmetterlingsblütlern)?",
        antwort="Rotklee und Weißklee",
        falsch=[
            "Deutsches Weidelgras und Wiesenlieschgras",
            "Nur Rotklee, alle anderen sind Gräser",
            "Alle vier genannten Arten",
        ],
        hinweis="Deutsches Weidelgras und Wiesenlieschgras sind Gräser; Kleearten sind Schmetterlingsblütler.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie 104",
    ),
    dict(
        id="SP5.2a", section="5", topic="Kleemüdigkeit",
        frage="Was ist die Hauptursache der Kleemüdigkeit?",
        antwort="Zu heiße Witterung oder Trockenheit während der Samenreife führen zu schlechtem Samenansatz",
        falsch=[
            "Zu milde Wintertemperaturen im Januar",
            "Zu hohe Phosphatdüngung",
            "Zu geringe Kalkgabe auf dem Feld",
        ],
        hinweis="Weitere Auslöser: schlechte Bestäubung und samenbürtige Krankheiten wie Kleekrebs und Samenbrand.",
        quelle="Prüfungsaufgabe 5.2",
    ),
    dict(
        id="SP5.2b", section="5", topic="Kleemüdigkeit",
        frage="Welche vorbeugende Maßnahme gegen Kleemüdigkeit ist wirksam?",
        antwort="Befallene Flächen rechtzeitig vor der Samenreife mähen oder hacken",
        falsch=[
            "Das Saatgut aus befallenen Beständen für den Nachbau verwenden",
            "Die Samen reifen lassen und erst nach der Ernte mähen",
            "Die Flächen mehrere Jahre nur als Grünland nutzen",
        ],
        hinweis="Ziel ist es, keimfähige Samen gar nicht erst entstehen zu lassen.",
        quelle="Prüfungsaufgabe 5.2",
    ),
    dict(
        id="SP5.5a", section="5", topic="Mais",
        frage="Was bedeutet „einhäusig-getrenntgeschlechtlich“ beim Mais?",
        antwort="Männliche und weibliche Blütenorgane sitzen getrennt an derselben Pflanze (Rispe und Kolben)",
        falsch=[
            "Männliche und weibliche Blüten sitzen an getrennten Pflanzen",
            "Die Pflanze wechselt während des Wachstums ihr Geschlecht",
            "Jede Pflanze trägt entweder nur männliche oder nur weibliche Blüten",
        ],
        hinweis="Getrenntgeschlechtlich heißt: Blütenorgane getrennt; einhäusig heißt: beides an derselben Pflanze.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie 30",
    ),
    dict(
        id="SP5.5b", section="5", topic="Mais",
        frage="Was versteht man beim Mais unter „Fremdbefruchter“?",
        antwort="Die Befruchtung erfolgt durch Pollen einer anderen Pflanze – Pollen wird durch Wind und Insekten übertragen",
        falsch=[
            "Die Pflanze bestäubt sich mit dem eigenen Pollen desselben Individuums",
            "Nur Insekten können den Mais befruchten",
            "Fremdbefruchtung erhöht den Homozygotiegrad der Nachkommen",
        ],
        hinweis="Die Folge ist ein hoher Heterozygotiegrad – die Basis der Hybridzüchtung.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie 30",
    ),
    dict(
        id="SP5.7", section="5", topic="Maiszünsler",
        frage="Welche indirekte Maßnahme reduziert den Maiszünslerbefall am wirksamsten?",
        antwort="Sauberes und tiefes Unterpflügen der befallenen Maisstoppel",
        falsch=[
            "Möglichst frühe Aussaat des Silomais im April",
            "Anbau von Silomais in jedem Jahr",
            "Ausbringen von Kalk auf die Maisfläche",
        ],
        hinweis="Weitere Maßnahmen: biologische Bekämpfung mit der Trichogramma-Schlupfwespe, chemische Behandlung nach amtlichem Warndienst.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie 55",
    ),
    dict(
        id="SP5.8", section="5", topic="Maisnutzung",
        frage="Welche Nutzungsformen von Mais sind üblich?",
        antwort="Als Silomais (Ganzpflanze, siliert) oder als Körnermais",
        falsch=[
            "Ausschließlich als Körnerfutter in der Kükenaufzucht",
            "Als Dünger in die Furche eingearbeitet",
            "Als Gründüngung untergepflügt",
        ],
        hinweis="Weitere Formen: Spross- und Blättermais, Corn-Cob-Mix, Maisstroh als Rauhfutter und Substrat für die Biogasanlage.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie 105",
    ),
    dict(
        id="SP5.2c", section="5", topic="Leguminosen",
        frage="Warum wird im Kleegrasbau auf eine ausreichende Phosphorversorgung geachtet?",
        antwort="Weil die Leguminosen sehr hohe Phosphorentzüge aufweisen (etwa 100–120 kg/ha)",
        falsch=[
            "Weil Phosphor den Kaliumbedarf der Gräser ersetzt",
            "Weil Phosphor im Kleegras generell nicht mobilisiert wird",
            "Weil Phosphor die Samenbildung der Leguminosen verhindert",
        ],
        hinweis="Zusätzlich wird die Kalkung möglichst vor dem Futterbau durchgeführt.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie 122",
    ),
    # ---------------- Schwerpunkt Grünland ----------------
    dict(
        id="SP6.1", section="6", topic="Grünlandbegriffe",
        frage="Worin unterscheiden sich absolutes und fakultatives Grünland?",
        antwort="Absolutes Grünland ist nicht anders nutzbar (z. B. Hanglage, Staunässe); fakultatives Grünland wäre auch als Acker nutzbar",
        falsch=[
            "Absolutes Grünland wird nur beweidet, fakultatives Grünland nur geschnitten",
            "Absolutes Grünland liegt immer im Tal, fakultatives Grünland immer am Hang",
            "Es gibt keinen Unterschied, beide Begriffe sind synonym",
        ],
        hinweis="Beim fakultativen Grünland erfolgt die Ackernutzung aus betrieblichen Gründen nicht.",
        quelle="Grundlagen GL-Bewirtschaftung BiLa Bayern, Folie Allgemeines zu Dauergrünland",
    ),
    dict(
        id="SP6.2", section="6", topic="Standort",
        frage="Welche Standortbedingungen kennzeichnen absolutes Grünland?",
        antwort="Hanglage, Staunässe, Überschwemmungsgefahr und ungünstige Bodenauflagen",
        falsch=["Trockene, schwach gedüngte Ackerflächen", "Südlagen mit tiefgründigem Lössboden", "Flächen mit Winterweizen in der Fruchtfolge"],
        hinweis="Der Boden ist zu nass, zu steil oder aus anderen Gründen ackerbaulich nicht nutzbar.",
        quelle="Grundlagen GL-Bewirtschaftung BiLa Bayern, Folie Allgemeines zu Dauergrünland",
    ),
    dict(
        id="SP6.3", section="6", topic="Bewirtschaftungsfehler",
        frage="Welcher Bewirtschaftungsfehler führt zu einer lückigen Narbe und zunehmender Verunkrautung?",
        antwort="Zu tiefes Mähen und zu starke Nutzung (Überweidung)",
        falsch=[
            "Zu hohes Mähen und zu früher Schnitt",
            "Zu geringe Düngung und zu später Schnitt",
            "Zu geringe Nutzung und falscher Erntetermin",
        ],
        hinweis="Wird die Grundnarbe verletzt, muss die Fläche meist nachgesät werden.",
        quelle="Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 2/4",
    ),
    dict(
        id="SP6.4a", section="6", topic="Gräser",
        frage="Wie unterscheidet sich das Welsche Weidelgras vom Deutschen Weidelgras?",
        antwort="Es hat eine höhere Ertragsleistung und höhere Futterqualität",
        falsch=[
            "Es ist deutlich winterhärter und ertragsärmer",
            "Es ist weniger ertragreich und wird nur zur Saatgutproduktion angebaut",
            "Es hat eine frühere Reife und einen höheren Rohfasergehalt",
        ],
        hinweis="Das Deutsche Weidelgras ist demgegenüber winterhärter und deshalb in weidelgrasunsicheren Gebieten im Vorteil.",
        quelle="BiLa 25-27 Ackerfutterbau, Folie Gräserarten",
    ),
    dict(
        id="SP6.4b", section="6", topic="Nachsaat",
        frage="Welche Voraussetzung ist für eine erfolgreiche Nachsaat auf Grünland entscheidend?",
        antwort="Die Narbe wird oberflächlich aufgerissen und die Saat flach in den feuchten Boden eingebracht",
        falsch=[
            "Die Saatgutmenge wird im Verhältnis 3 : 1 erhöht",
            "Die Narbe bleibt unberührt, damit die alten Bestände erhalten bleiben",
            "Die Nachsaat erfolgt ausschließlich nach dem ersten Schnitt",
        ],
        hinweis="Nachgesät wird nur bei nicht schließenden Nestern oder großen Lücken (ab etwa 10 cm).",
        quelle="Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 3/4",
    ),
    dict(
        id="SP6.5", section="6", topic="Grassilage",
        frage="Wie können Sie die Qualität der Grassilage positiv beeinflussen?",
        antwort="Möglichst früh und bei trockener Witterung schneiden und eine nicht zu niedrige Schnitthöhe wählen",
        falsch=[
            "Möglichst spät bei feuchter Witterung mähen und tief schneiden",
            "Das Gras erst nach Feldumtrieb silieren, um den Ertrag zu erhöhen",
            "Nach der Mahd das Gras mehrere Tage ungewendet liegen lassen",
        ],
        hinweis="Wichtig für die Silierbarkeit: junges, faserarmes Material, wenig Erdbesatz und zügiges Silieren mit ausreichender Säurebildung.",
        quelle="Grundlagen GL-Bewirtschaftung BiLa Bayern Teil 2/3",
    ),
    dict(
        id="SP6.6", section="6", topic="Siloraum",
        frage="Sie bewirtschaften 55 ha Grünland (5 Schnitte, 280 dt FM/ha, 35 % TS) und pachten 10 ha mit gleichem Ertrag. Reicht der Platz im Fahrsilo (3.200 m³ bei 200 kg TM/m³)?",
        antwort="Ja, knapp – 637 t TM entsprechen rund 3.185 m³ von 3.200 m³ Platz",
        falsch=[
            "Nein, es werden rund 6.370 m³ benötigt",
            "Nein, es werden rund 3.720 m³ benötigt",
            "Nein, es werden rund 1.870 m³ benötigt",
        ],
        hinweis="65 ha × 280 dt = 18.200 dt FM × 0,35 = 6.370 dt TM = 637 t TM; 637.000 kg ÷ 200 kg/m³ = 3.185 m³.",
        quelle="Prüfungsaufgabe 6.6",
    ),
    # ---------------- Schwerpunkt Waldbau ----------------
    dict(
        id="SP7.1a", section="7", topic="Naturverjüngung",
        frage="Welche Vorteile hat die Naturverjüngung gegenüber der Pflanzung?",
        antwort="Ungestörte Wurzelentwicklung und geringere Gefährdung durch Wild und Mäuse",
        falsch=[
            "Höhere Ertragsleistung und gleichmäßiger Bestand",
            "Kürzere Kulturdauer ohne Pflegeaufwand",
            "Wurzelschutz durch das Fehlen von Mäusen",
        ],
        hinweis="Weitere Vorteile: Ersparnis von Zeit und Geld sowie Schutz durch den Altbestand.",
        quelle="2025_BiLa_Grundlagen_Waldwirtschaft, Folie 99",
    ),
    dict(
        id="SP7.1b", section="7", topic="Naturverjüngung",
        frage="Welche Voraussetzung muss für das Gelingen der Naturverjüngung erfüllt sein?",
        antwort="Vorhanden sind geeignete, vitale Altbäume und ein stabiler Altbestand für langsam steigende Lichtgaben",
        falsch=["Ein dichter Jungwuchs aus dem Vorjahr", "Eine hohe Stickstoffversorgung des Bodens", "Eine vollständig freigestellte Fläche"],
        hinweis="Außerdem wichtig: geringe Verunkrautung des Bodens.",
        quelle="2025_BiLa_Grundlagen_Waldwirtschaft, Folie 99",
    ),
    dict(
        id="SP7.2", section="7", topic="Monokultur",
        frage="Welche Nachteile haben Fichten-Reinkulturen?",
        antwort="Ein hohes Risiko für Sturm-, Dürre- und Käferschäden – die Gefährdung wiegt die hohen Erträge auf",
        falsch=[
            "Zu geringe Bodenwasserversorgung durch flache Wurzeln",
            "Zu hoher Nährstoffanspruch des Holzes",
            "Fehlende Winterhärte durch die geringe Höhenlage",
        ],
        hinweis="Der Wohlfühlbereich der Fichte in Bayern wird sich durch den Klimawandel weiter verkleinern – die Mischung mit anderen Baumarten wird wichtiger.",
        quelle="2025_BiLa_Grundlagen_Waldwirtschaft, Folie 64/65",
    ),
    dict(
        id="SP7.4a", section="7", topic="Pflanzware",
        frage="Woran erkennen Sie minderwertige Pflanzware?",
        antwort="Nicht frische, geschädigte Pflanzen mit verbogenen Wurzeln und ohne eindeutigen Haupttrieb",
        falsch=[
            "Übergroße Pflanzen",
            "Eine geringe Pflanzhöhe bei Sämlingen",
            "Fehlende Nadelstreu im Pflanzloch",
        ],
        hinweis="Gute Ware ist frisch, gesund, vital, ohne Verletzungen, gerade, mit eindeutigem Haupttrieb und ohne Wurzeldeformationen.",
        quelle="2025_BiLa_Grundlagen_Waldwirtschaft, Folie 108",
    ),
    dict(
        id="SP7.4b", section="7", topic="Pflanzverfahren",
        frage="Warum wird das Pflanzen mit dem Hohlspaten bevorzugt?",
        antwort="Weil es wurzelschonend ist und auch breitwurzelnde Tiefwurzler ohne Wurzelverformungen setzt",
        falsch=[
            "Weil die Wurzeln dabei immer um 20 cm gekürzt werden",
            "Weil das Pflanzloch mit Dünger angereichert wird",
            "Weil es nur auf sehr steinigen Böden eingesetzt wird",
        ],
        hinweis="Nachteil: Der Boden darf nicht zu steinig oder tonig sein. Vorteil: für alle Baumarten geeignet und leicht zu erlernen.",
        quelle="2025_BiLa_Grundlagen_Waldwirtschaft, Folie 121",
    ),
    dict(
        id="SP7.5", section="7", topic="Holzverkauf",
        frage="Sie liefern 22 fm Güteklasse B zu 60 €/fm und 8 fm Güteklasse C zu 40 €/fm. Wie hoch ist der Verkaufserlös inklusive 5,5 % MwSt.?",
        antwort="1.730,20 €",
        falsch=["1.640,00 €", "1.550,20 €", "2.056,00 €"],
        hinweis="22 × 60 € + 8 × 40 € = 1.640 € netto; 1.640 € × 1,055 = 1.730,20 € brutto.",
        quelle="Prüfungsaufgabe 7.5.3",
    ),
    dict(
        id="SP7.6a", section="7", topic="Unfallschutz",
        frage="Welche Regel gilt für den Fallbereich bei Fällarbeiten?",
        antwort="Der Fallbereich wird abgesperrt – dort dürfen sich nur die mit dem Fällen beschäftigten Personen aufhalten",
        falsch=[
            "Alle Personen im Bestand dürfen den Fällvorgang aus sicherer Entfernung beobachten",
            "Eisenkeile sind zu verwenden, damit der Baum sicherer fällt",
            "Es darf auch bei starkem Wind und in der Dämmerung gefällt werden",
        ],
        hinweis="Weitere Regeln: Fallkerb anlegen, Achtungsruf beim Fällschnitt, Rückweichen anlegen, keine Alleinarbeit mit Motorsäge oder Seilwinde.",
        quelle="2025_BiLa_Holz_Arbeitssicherheit, Unfallverhütungsvorschrift Forsten § 5",
    ),
    dict(
        id="SP7.6b", section="7", topic="Unfallschutz",
        frage="Welche persönliche Schutzausrüstung muss bei der Waldarbeit getragen werden?",
        antwort="Schutzhelm, Schutzhose mit Schnittschutz, Sicherheitsschuhe sowie Gehör- und Gesichtsschutz",
        falsch=[
            "Sonnencreme und Regenjacke",
            "Fahrradhelm und Warnweste",
            "Lederschürze und Gummistiefeln allein",
        ],
        hinweis="71 % aller Unfälle bei der Waldarbeit passieren bei der Holzernte und der Bestandspflege.",
        quelle="2025_BiLa_Holz_Arbeitssicherheit, Folie 21/22",
    ),
]
